import { Category, Product, Service, ContactInfo } from '@/types/jewelry';

export const categories: Category[] = [
  {
    id: '1',
    name: 'Gold Rings',
    slug: 'gold-rings',
    description: 'Elegant gold rings for every occasion',
    image: 'https://images.pexels.com/photos/1721944/pexels-photo-1721944.jpeg?auto=compress&cs=tinysrgb&w=600',
    productCount: 24,
  },
  {
    id: '2',
    name: 'Bracelets',
    slug: 'bracelets',
    description: 'Beautiful gold and diamond bracelets',
    image: 'https://images.pexels.com/photos/1454191/pexels-photo-1454191.jpeg?auto=compress&cs=tinysrgb&w=600',
    productCount: 18,
  },
  {
    id: '3',
    name: 'Earrings',
    slug: 'earrings',
    description: 'Traditional and modern earring designs',
    image: 'https://images.pexels.com/photos/1391480/pexels-photo-1391480.jpeg?auto=compress&cs=tinysrgb&w=600',
    productCount: 32,
  },
  {
    id: '4',
    name: 'Necklaces',
    slug: 'necklaces',
    description: 'Stunning necklaces for special moments',
    image: 'https://images.pexels.com/photos/1721555/pexels-photo-1721555.jpeg?auto=compress&cs=tinysrgb&w=600',
    productCount: 28,
  },
  {
    id: '5',
    name: 'Bangles',
    slug: 'bangles',
    description: 'Traditional gold bangles and kadas',
    image: 'https://images.pexels.com/photos/1726254/pexels-photo-1726254.jpeg?auto=compress&cs=tinysrgb&w=600',
    productCount: 22,
  },
  {
    id: '6',
    name: 'Pendants',
    slug: 'pendants',
    description: 'Exquisite gold and diamond pendants',
    image: 'https://images.pexels.com/photos/1453769/pexels-photo-1453769.jpeg?auto=compress&cs=tinysrgb&w=600',
    productCount: 16,
  },
  {
    id: '7',
    name: 'Silver Unique Items',
    slug: 'silver-items',
    description: 'Unique and exquisite silver items',
    image: '/prods/silver-items/charan-paduka/charan-paduka (1).jpg',
    productCount: 43,
  },
  {
    id: '8',
    name: 'Laddu Gopal Items',
    slug: 'laddu-gopal-items',
    description: 'Unique and exquisite laddu gopal items',
    image: '/prods/laddu-gopal-items/laddu-gopal-balti/laddu-gopal-balti (1).jpg',
    productCount: 11,
  },
];

export const services: Service[] = [
  {
    id: '1',
    title: 'Digital Gold',
    description: 'Invest in 24k pure gold digitally with instant buying and selling',
    icon: 'smartphone',
    features: ['24k Pure Gold', 'Instant Transactions', 'Secure Storage', 'Real-time Rates'],
  },
  {
    id: '2',
    title: 'Gold SIP',
    description: 'Systematic Investment Plan for gold with flexible monthly payments',
    icon: 'trending-up',
    features: ['Monthly SIP', 'Flexible Amount', 'Long-term Growth', 'Tax Benefits'],
  },
  {
    id: '3',
    title: 'E-Gift Card',
    description: 'Perfect gift for your loved ones, redeemable across all jewelry',
    icon: 'gift',
    features: ['Instant Delivery', 'Custom Amount', 'No Expiry', 'Easy Redemption'],
  },
  {
    id: '4',
    title: 'Custom Jewelry',
    description: 'Design your own unique pieces with our expert craftsmen',
    icon: 'pen-tool',
    features: ['Personal Design', 'Expert Crafting', 'Premium Materials', 'Lifetime Service'],
  },
];

export const sampleProducts: Product[] = [
  {
    id: '1',
    name: 'Traditional Gold Ring',
    category: 'gold-rings',
    price: 45000,
    originalPrice: 48000,
    images: ['https://images.pexels.com/photos/1721944/pexels-photo-1721944.jpeg?auto=compress&cs=tinysrgb&w=600'],
    description: 'Elegant 22k gold ring with intricate traditional design',
    material: '22k Gold',
    weight: '8.5g',
    purity: '916',
    inStock: true,
    featured: true,
  },
  {
    id: '2',
    name: 'Diamond Bracelet',
    category: 'bracelets',
    price: 125000,
    images: ['https://images.pexels.com/photos/1454191/pexels-photo-1454191.jpeg?auto=compress&cs=tinysrgb&w=600'],
    description: 'Stunning diamond bracelet with 18k gold setting',
    material: '18k Gold + Diamonds',
    weight: '12.3g',
    purity: '750',
    inStock: true,
    featured: true,
  },
  {
    id: '3',
    name: 'Charan Paduka',
    category: 'silver-items',
    price: 125000,
    images: ['/prods/silver-items/charan-paduka/charan-paduka (1).jpg', '/prods/silver-items/charan-paduka/charan-paduka (2).jpg', '/prods/silver-items/charan-paduka/charan-paduka (3).jpg', '/prods/silver-items/charan-paduka/charan-paduka (4).jpg', '/prods/silver-items/charan-paduka/charan-paduka (5).jpg', '/prods/silver-items/charan-paduka/charan-paduka (6).jpg', '/prods/silver-items/charan-paduka/charan-paduka (7).jpg', '/prods/silver-items/charan-paduka/charan-paduka (8).jpg', '/prods/silver-items/charan-paduka/charan-paduka (9).jpg', '/prods/silver-items/charan-paduka/charan-paduka (10).jpg', '/prods/silver-items/charan-paduka/charan-paduka (11).jpg', '/prods/silver-items/charan-paduka/charan-paduka (12).jpg', '/prods/silver-items/charan-paduka/charan-paduka (13).jpg'],
    description: 'Stunning Silver Charan Paduka',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '4',
    name: 'Agarbatti Stand',
    category: 'silver-items',
    price: 125000,
    images: ['/prods/silver-items/agarbatti-stand/agarbatti-stand (1).jpg', '/prods/silver-items/agarbatti-stand/agarbatti-stand (2).jpg', '/prods/silver-items/agarbatti-stand/agarbatti-stand (3).jpg', '/prods/silver-items/agarbatti-stand/agarbatti-stand (4).jpg', '/prods/silver-items/agarbatti-stand/agarbatti-stand (5).jpg', '/prods/silver-items/agarbatti-stand/agarbatti-stand (6).jpg', '/prods/silver-items/agarbatti-stand/agarbatti-stand (7).jpg', '/prods/silver-items/agarbatti-stand/agarbatti-stand (8).jpg'],
    description: 'Stunning Silver Agarbatti Stand',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '5',
    name: 'Bahumukhi Deepak',
    category: 'silver-items',
    price: 125000,
    images: ['/prods/silver-items/bahumukhi-deepak/bahumukhi-deepak (1).jpg', '/prods/silver-items/bahumukhi-deepak/bahumukhi-deepak (2).jpg', '/prods/silver-items/bahumukhi-deepak/bahumukhi-deepak (3).jpg', '/prods/silver-items/bahumukhi-deepak/bahumukhi-deepak (4).jpg'],
    description: 'Stunning Silver Bahumukhi Deepak',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '6',
    name: 'Chaaku',
    category: 'silver-items',
    price: 125000,
    images: ['/prods/silver-items/chaaku/chaaku (1).jpg', '/prods/silver-items/chaaku/chaaku (2).jpg', '/prods/silver-items/chaaku/chaaku (3).jpg'],
    description: 'Stunning Silver Chaaku',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '7',
    name: 'Chanwar(only hattha)',
    category: 'silver-items',
    price: 125000,
    images: ['/prods/silver-items/chanwar-only-hattha/chaanvar(only hattha) (1).jpg', '/prods/silver-items/chanwar-only-hattha/chaanvar(only hattha) (2).jpg', '/prods/silver-items/chanwar-only-hattha/chaanvar(only hattha) (3).jpg'],
    description: 'Stunning Silver Chanwar(only hattha)',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '8',
    name: 'Kachhua Chaupada',
    category: 'silver-items',
    price: 125000,
    images: ['/prods/silver-items/chaupda/kachhua-chaupda (1).jpg', '/prods/silver-items/chaupda/kachhua-chaupda (2).jpg'],
    description: 'Stunning Silver KachhuaChaupada',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '9',
    name: 'Mor Chaupada',
    category: 'silver-items',
    price: 125000,
    images: ['/prods/silver-items/chaupda/mor-chaupda (1).jpg', '/prods/silver-items/chaupda/mor-chaupda (2).jpg'],
    description: 'Stunning Silver Mor Chaupada',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '10',
    name: 'Chilam',
    category: 'silver-items',
    price: 125000,
    images: ['/prods/silver-items/chillam/chillam (1).jpg', '/prods/silver-items/chillam/chillam (2).jpg', '/prods/silver-items/chillam/chillam (3).jpg', '/prods/silver-items/chillam/chillam (4).jpg', "/prods/silver-items/chillam/chillam (5).jpg"],
    description: 'Stunning Silver Chilam',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '11',
    name: 'Damru Trisul',
    category: 'silver-items',
    price: 125000,
    images: ['/prods/silver-items/damru-trisul/damru-trisul (1).jpg', '/prods/silver-items/damru-trisul/damru-trisul (2).jpg'],
    description: 'Stunning Silver Damru Trisul',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '12',
    name: 'Deepak Stand',
    category: 'silver-items',
    price: 125000,
    images: ['/prods/silver-items/deepak-stand/deepak-stand (1).jpg', '/prods/silver-items/deepak-stand/deepak-stand (2).jpg'],
    description: 'Stunning Silver Deepak Stand',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '13',
    name: 'Dibbi',
    category: 'silver-items',
    price: 125000,
    images: ['/prods/silver-items/dibbi/dibbi (1).jpg', '/prods/silver-items/dibbi/dibbi (2).jpg', "/prods/silver-items/dibbi/dibbi (3).jpg", "/prods/silver-items/dibbi/dibbi (4).jpg", "/prods/silver-items/dibbi/dibbi (5).jpg", "/prods/silver-items/dibbi/dibbi (6).jpg", "/prods/silver-items/dibbi/dibbi (7).jpg", "/prods/silver-items/dibbi/dibbi (8).jpg", "/prods/silver-items/dibbi/dibbi (9).jpg", "/prods/silver-items/dibbi/dibbi (10).jpg", "/prods/silver-items/dibbi/dibbi (11).jpg", "/prods/silver-items/dibbi/dibbi (12).jpg", "/prods/silver-items/dibbi/dibbi (13).jpg", "/prods/silver-items/dibbi/dibbi (14).jpg", "/prods/silver-items/dibbi/dibbi (15).jpg", "/prods/silver-items/dibbi/dibbi (16).jpg"],
    description: 'Stunning Silver Dibbi',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '14',
    name: 'Firkali',
    category: 'silver-items',
    price: 125000,
    images: ['/prods/silver-items/firkali/firkli (1).jpg', '/prods/silver-items/firkali/firkli (2).jpg', "/prods/silver-items/firkali/firkli (3).jpg", "/prods/silver-items/firkali/firkli (4).jpg", "/prods/silver-items/firkali/firkli (5).jpg", "/prods/silver-items/firkali/firkli (6).jpg", "/prods/silver-items/firkali/firkli (7).jpg", "/prods/silver-items/firkali/firkli (8).jpg", "/prods/silver-items/firkali/firkli (9).jpg"],
    description: 'Stunning Silver Firkali',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '15',
    name: 'Gaaya',
    category: 'silver-items',
    price: 125000,
    images: ['/prods/silver-items/gaay/gaay (1).jpg', '/prods/silver-items/gaay/gaay (2).jpg', "/prods/silver-items/gaay/gaay (3).jpg", "/prods/silver-items/gaay/gaay (4).jpg", "/prods/silver-items/gaay/gaay (5).jpg", "/prods/silver-items/gaay/gaay (6).jpg", "/prods/silver-items/gaay/gaay (7).jpg", "/prods/silver-items/gaay/gaay (8).jpg", "/prods/silver-items/gaay/gaay (9).jpg", "/prods/silver-items/gaay/gaay (10).jpg", "/prods/silver-items/gaay/gaay (11).jpg", "/prods/silver-items/gaay/gaay (12).jpg", "/prods/silver-items/gaay/gaay (13).jpg", "/prods/silver-items/gaay/gaay (14).jpg", "/prods/silver-items/gaay/gaay (15).jpg", "/prods/silver-items/gaay/gaay (16).jpg"],
    description: 'Stunning Silver Gaaya',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '16',
    name: 'Ghatti',
    category: 'silver-items',
    price: 125000,
    images: ['/prods/silver-items/ghatti/ghatti (1).jpg', '/prods/silver-items/ghatti/ghatti (2).jpg', "/prods/silver-items/ghatti/ghatti (3).jpg", "/prods/silver-items/ghatti/ghatti (4).jpg", "/prods/silver-items/ghatti/ghatti (5).jpg", "/prods/silver-items/ghatti/ghatti (6).jpg", "/prods/silver-items/ghatti/ghatti (7).jpg", "/prods/silver-items/ghatti/ghatti (8).jpg", "/prods/silver-items/ghatti/ghatti (9).jpg", "/prods/silver-items/ghatti/ghatti (10).jpg", "/prods/silver-items/ghatti/ghatti (11).jpg", "/prods/silver-items/ghatti/ghatti (12).jpg", "/prods/silver-items/ghatti/ghatti (13).jpg", "/prods/silver-items/ghatti/ghatti (14).jpg", "/prods/silver-items/ghatti/ghatti (15).jpg", "/prods/silver-items/ghatti/ghatti (16).jpg"],
    description: 'Stunning Silver Ghatti',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '18',
    name: 'Chhota Gada',
    category: 'silver-items',
    price: 125000,
    images: ['/prods/silver-items/ghota-gada/gada-ghota (1).jpg', '/prods/silver-items/ghota-gada/gada-ghota (2).jpg', "/prods/silver-items/ghota-gada/gada-ghota (3).jpg", "/prods/silver-items/ghota-gada/gada-ghota (4).jpg", "/prods/silver-items/ghota-gada/gada-ghota (5).jpg", "/prods/silver-items/ghota-gada/gada-ghota (6).jpg", "/prods/silver-items/ghota-gada/gada-ghota (7).jpg", "/prods/silver-items/ghota-gada/gada-ghota (8).jpg", "/prods/silver-items/ghota-gada/gada-ghota (9).jpg", "/prods/silver-items/ghota-gada/gada-ghota (10).jpg", "/prods/silver-items/ghota-gada/gada-ghota (11).jpg", "/prods/silver-items/ghota-gada/gada-ghota (12).jpg", "/prods/silver-items/ghota-gada/gada-ghota (13).jpg", "/prods/silver-items/ghota-gada/gada-ghota (14).jpg", "/prods/silver-items/ghota-gada/gada-ghota (15).jpg", "/prods/silver-items/ghota-gada/gada-ghota (16).jpg", "/prods/silver-items/ghota-gada/gada-ghota (17).jpg", "/prods/silver-items/ghota-gada/gada-ghota (18).jpg", "/prods/silver-items/ghota-gada/gada-ghota (19).jpg", "/prods/silver-items/ghota-gada/gada-ghota (20).jpg", "/prods/silver-items/ghota-gada/gada-ghota (21).jpg"],
    description: 'Stunning Silver Chhota Gada',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '19',
    name: 'Handle Deepak',
    category: 'silver-items',
    price: 125000,
    images: ['/prods/silver-items/handle-deepak/handle-deepak (1).jpg', '/prods/silver-items/handle-deepak/handle-deepak (2).jpg'],
    description: 'Stunning Silver Handle Deepak',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '20',
    name: 'Hollow Murti',
    category: 'silver-items',
    price: 125000,
    images: ['/prods/silver-items/hollow-moorti/hollow-moorti (1).jpg', '/prods/silver-items/hollow-moorti/hollow-moorti (2).jpg', "/prods/silver-items/hollow-moorti/hollow-moorti (3).jpg", "/prods/silver-items/hollow-moorti/hollow-moorti (4).jpg", "/prods/silver-items/hollow-moorti/hollow-moorti (5).jpg", "/prods/silver-items/hollow-moorti/hollow-moorti (6).jpg", "/prods/silver-items/hollow-moorti/hollow-moorti (7).jpg", "/prods/silver-items/hollow-moorti/hollow-moorti (8).jpg", "/prods/silver-items/hollow-moorti/hollow-moorti (9).jpg"],
    description: 'Stunning Silver Hollow Murti',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '21',
    name: 'Hollow Stand Murti',
    category: 'silver-items',
    price: 125000,
    images: ['/prods/silver-items/hollow-stand-moorti/hollow-stand-moorti (1).jpg', '/prods/silver-items/hollow-stand-moorti/hollow-stand-moorti (2).jpg', "/prods/silver-items/hollow-stand-moorti/hollow-stand-moorti (3).jpg", "/prods/silver-items/hollow-stand-moorti/hollow-stand-moorti (4).jpg", "/prods/silver-items/hollow-stand-moorti/hollow-stand-moorti (5).jpg", "/prods/silver-items/hollow-stand-moorti/hollow-stand-moorti (6).jpg", "/prods/silver-items/hollow-stand-moorti/hollow-stand-moorti (7).jpg", "/prods/silver-items/hollow-stand-moorti/hollow-stand-moorti (8).jpg"],
    description: 'Stunning Silver Hollow Stand Murti',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '22',
    name: 'Ittra Dani',
    category: 'silver-items',
    price: 125000,
    images: ['/prods/silver-items/ittra-dani/ittra-daani (1).jpg', '/prods/silver-items/ittra-dani/ittra-daani (2).jpg', "/prods/silver-items/ittra-dani/ittra-daani (3).jpg"],
    description: 'Stunning Silver Ittra Dani',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '23',
    name: 'Ittra Favvara',
    category: 'silver-items',
    price: 125000,
    images: ['/prods/silver-items/ittra-favvara/ittra-favvara (1).jpg', '/prods/silver-items/ittra-favvara/ittra-favvara (2).jpg', "/prods/silver-items/ittra-favvara/ittra-favvara (3).jpg", "/prods/silver-items/ittra-favvara/ittra-favvara (4).jpg"],
    description: 'Stunning Silver Ittra Favvara',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '24',
    name: 'Jaanvar',
    category: 'silver-items',
    price: 125000,
    images: ['/prods/silver-items/jaanvar/jaanvar (1).jpg', '/prods/silver-items/jaanvar/jaanvar (2).jpg', "/prods/silver-items/jaanvar/jaanvar (3).jpg", "/prods/silver-items/jaanvar/jaanvar (4).jpg", "/prods/silver-items/jaanvar/jaanvar (5).jpg"],
    description: 'Stunning Silver Jaanvar',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '24',
    name: 'Jaanvar Meena',
    category: 'silver-items',
    price: 125000,
    images: ['/prods/silver-items/janvar-meena/jaanvar-meena (1).jpg', '/prods/silver-items/janvar-meena/jaanvar-meena (2).jpg', "/prods/silver-items/janvar-meena/jaanvar-meena (3).jpg", "/prods/silver-items/janvar-meena/jaanvar-meena (4).jpg", "/prods/silver-items/janvar-meena/jaanvar-meena (5).jpg", "/prods/silver-items/janvar-meena/jaanvar-meena (6).jpg", "/prods/silver-items/janvar-meena/jaanvar-meena (7).jpg", "/prods/silver-items/janvar-meena/jaanvar-meena (8).jpg", "/prods/silver-items/janvar-meena/jaanvar-meena (9).jpg", "/prods/silver-items/janvar-meena/jaanvar-meena (10).jpg"],
    description: 'Stunning Silver Jaanvar Meena',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '25',
    name: 'Kalash',
    category: 'silver-items',
    price: 125000,
    images: ['/prods/silver-items/kalash/kalash (1).jpg', '/prods/silver-items/kalash/kalash (2).jpg', "/prods/silver-items/kalash/kalash (3).jpg", "/prods/silver-items/kalash/kalash (4).jpg", "/prods/silver-items/kalash/kalash (5).jpg", "/prods/silver-items/kalash/kalash (6).jpg", "/prods/silver-items/kalash/kalash (7).jpg", "/prods/silver-items/kalash/kalash (8).jpg", "/prods/silver-items/kalash/kalash (9).jpg"],
    description: 'Stunning Silver Kalash',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '26',
    name: 'Khedi Dibbi',
    category: 'silver-items',
    price: 125000,
    images: ['/prods/silver-items/khedi-dibbi/khedi-dibbi (1).jpg', '/prods/silver-items/khedi-dibbi/khedi-dibbi (2).jpg', "/prods/silver-items/khedi-dibbi/khedi-dibbi (3).jpg", "/prods/silver-items/khedi-dibbi/khedi-dibbi (4).jpg", "/prods/silver-items/khedi-dibbi/khedi-dibbi (5).jpg"],
    description: 'Stunning Silver Khedi Dibbi',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '27',
    name: 'Lakshmi Mata Deepak',
    category: 'silver-items',
    price: 125000,
    images: ['/prods/silver-items/lakshmi-mata-deepak/lakshmi-mata-deepak (1).jpg', '/prods/silver-items/lakshmi-mata-deepak/lakshmi-mata-deepak (2).jpg', "/prods/silver-items/lakshmi-mata-deepak/lakshmi-mata-deepak (3).jpg", "/prods/silver-items/lakshmi-mata-deepak/lakshmi-mata-deepak (4).jpg", "/prods/silver-items/lakshmi-mata-deepak/lakshmi-mata-deepak (5).jpg", "/prods/silver-items/lakshmi-mata-deepak/lakshmi-mata-deepak (6).jpg", "/prods/silver-items/lakshmi-mata-deepak/lakshmi-mata-deepak (7).jpg"],
    description: 'Stunning Silver Lakshmi Mata Deepak',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '27',
    name: 'Mandir Ghanti',
    category: 'silver-items',
    price: 125000,
    images: ['/prods/silver-items/mandir-ghanti/mandir-ghanti.jpg'],
    description: 'Stunning Silver Mandir Ghanti',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '28',
    name: 'Nada Pirohni',
    category: 'silver-items',
    price: 125000,
    images: ['/prods/silver-items/nada-pirohni/nada-pirohdi (1).jpg', '/prods/silver-items/nada-pirohni/nada-pirohdi (2).jpg'],
    description: 'Stunning Silver Nada Pirohni',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '29',
    name: 'Nandi',
    category: 'silver-items',
    price: 125000,
    images: ['/prods/silver-items/nandi/nandi (1).jpg', '/prods/silver-items/nandi/nandi (2).jpg'],
    description: 'Stunning Silver Nandi',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '30',
    name: 'Pakshi',
    category: 'silver-items',
    price: 125000,
    images: ['/prods/silver-items/pakshi/pakkshi (1).jpg', '/prods/silver-items/pakshi/pakkshi (2).jpg', "/prods/silver-items/pakshi/pakkshi (3).jpg", "/prods/silver-items/pakshi/pakkshi (4).jpg", "/prods/silver-items/pakshi/pakkshi (5).jpg", "/prods/silver-items/pakshi/pakkshi (6).jpg", "/prods/silver-items/pakshi/pakkshi (7).jpg", "/prods/silver-items/pakshi/pakkshi (8).jpg", "/prods/silver-items/pakshi/pakkshi (9).jpg", "/prods/silver-items/pakshi/pakkshi (10).jpg", "/prods/silver-items/pakshi/pakkshi (11).jpg"],
    description: 'Stunning Silver Pakshi',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '31',
    name: 'Pen',
    category: 'silver-items',
    price: 125000,
    images: ['/prods/silver-items/pen/pen (1).jpg', '/prods/silver-items/pen/pen (2).jpg', "/prods/silver-items/pen/pen (3).jpg", "/prods/silver-items/pen/pen (4).jpg", "/prods/silver-items/pen/pen (5).jpg", "/prods/silver-items/pen/pen (6).jpg", "/prods/silver-items/pen/pen (7).jpg", "/prods/silver-items/pen/pen (8).jpg", "/prods/silver-items/pen/pen (9).jpg", "/prods/silver-items/pen/pen (10).jpg", "/prods/silver-items/pen/pen (11).jpg"],
    description: 'Stunning Silver Pen',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '32',
    name: 'Ramjhara',
    category: 'silver-items',
    price: 125000,
    images: ['/prods/silver-items/ramjhara/ramjhara (1).jpg', '/prods/silver-items/ramjhara/ramjhara (2).jpg', "/prods/silver-items/ramjhara/ramjhara (3).jpg", "/prods/silver-items/ramjhara/ramjhara (4).jpg"],
    description: 'Stunning Silver Ramjhara',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '33',
    name: 'Rath',
    category: 'silver-items',
    price: 125000,
    images: ['/prods/silver-items/rath/surya-god-rath (1).jpg', '/prods/silver-items/rath/surya-god-rath (2).jpg', "/prods/silver-items/rath/surya-god-rath (3).jpg", "/prods/silver-items/rath/surya-god-rath (4).jpg", "/prods/silver-items/rath/surya-god-rath (5).jpg", "/prods/silver-items/rath/surya-god-rath (6).jpg", "/prods/silver-items/rath/surya-god-rath (7).jpg", "/prods/silver-items/rath/surya-god-rath (8).jpg", "/prods/silver-items/rath/surya-god-rath (9).jpg", "/prods/silver-items/rath/surya-god-rath (10).jpg", "/prods/silver-items/rath/surya-god-rath (11).jpg"],
    description: 'Stunning Silver Rath',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '34',
    name: 'Sada Deepak',
    category: 'silver-items',
    price: 125000,
    images: ['/prods/silver-items/sada-deepak/sada-deepak (1).jpg', '/prods/silver-items/sada-deepak/sada-deepak (2).jpg', "/prods/silver-items/sada-deepak/sada-deepak (3).jpg", "/prods/silver-items/sada-deepak/sada-deepak (4).jpg", "/prods/silver-items/sada-deepak/sada-deepak (5).jpg", "/prods/silver-items/sada-deepak/sada-deepak (6).jpg", "/prods/silver-items/sada-deepak/sada-deepak (7).jpg", "/prods/silver-items/sada-deepak/sada-deepak (8).jpg", "/prods/silver-items/sada-deepak/sada-deepak (9).jpg", "/prods/silver-items/sada-deepak/sada-deepak (10).jpg", "/prods/silver-items/sada-deepak/sada-deepak (11).jpg"],
    description: 'Stunning Silver Sada Deepak',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '35',
    name: 'Sadi Pin',
    category: 'silver-items',
    price: 125000,
    images: ['/prods/silver-items/sadi-pin/sadi-pin (1).jpg', '/prods/silver-items/sadi-pin/sadi-pin (2).jpg', "/prods/silver-items/sadi-pin/sadi-pin (3).jpg", "/prods/silver-items/sadi-pin/sadi-pin (4).jpg", "/prods/silver-items/sadi-pin/sadi-pin (5).jpg", "/prods/silver-items/sadi-pin/sadi-pin (6).jpg", "/prods/silver-items/sadi-pin/sadi-pin (7).jpg", "/prods/silver-items/sadi-pin/sadi-pin (8).jpg", "/prods/silver-items/sadi-pin/sadi-pin (9).jpg", "/prods/silver-items/sadi-pin/sadi-pin (10).jpg", "/prods/silver-items/sadi-pin/sadi-pin (11).jpg"],
    description: 'Stunning Silver Sadi Pin',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '36',
    name: 'Shivling Jalhari',
    category: 'silver-items',
    price: 125000,
    images: ['/prods/silver-items/shivling-jalheri/shivling-jalheri (1).jpg', '/prods/silver-items/shivling-jalheri/shivling-jalheri (2).jpg', "/prods/silver-items/shivling-jalheri/shivling-jalheri (3).jpg", "/prods/silver-items/shivling-jalheri/shivling-jalheri (4).jpg", "/prods/silver-items/shivling-jalheri/shivling-jalheri (5).jpg"],
    description: 'Stunning Silver Shivling Jalhari',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '37',
    name: 'Shivling Jhari',
    category: 'silver-items',
    price: 125000,
    images: ['/prods/silver-items/shivling-jhari/shivlink-jhari (1).jpg', '/prods/silver-items/shivling-jhari/shivlink-jhari (2).jpg', "/prods/silver-items/shivling-jhari/shivlink-jhari (3).jpg", "/prods/silver-items/shivling-jhari/shivlink-jhari (4).jpg", "/prods/silver-items/shivling-jhari/shivlink-jhari (5).jpg"],
    description: 'Stunning Silver Shivling Jhari',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '38',
    name: 'Shree Shyam Nishan',
    category: 'silver-items',
    price: 125000,
    images: ['/prods/silver-items/shree-shyam-nishan/shri-shyam-nishan (1).jpg', '/prods/silver-items/shree-shyam-nishan/shri-shyam-nishan (2).jpg', '/prods/silver-items/shree-shyam-nishan/shri-shyam-nishan (3).jpg'],
    description: 'Stunning Silver Shree Shyam Nishan',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '39',
    name: 'Sighdi Borsi',
    category: 'silver-items',
    price: 125000,
    images: ['/prods/silver-items/sighdi-borsi/sighadi (1).jpg', '/prods/silver-items/sighdi-borsi/sighadi (2).jpg', '/prods/silver-items/sighdi-borsi/sighadi (3).jpg'],
    description: 'Stunning Silver Sighdi Borsi',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '40',
    name: 'Sindoor Dani',
    category: 'silver-items',
    price: 125000,
    images: ['/prods/silver-items/sindoor-dani/sindoor-dani (1).jpg', '/prods/silver-items/sindoor-dani/sindoor-dani (2).jpg', '/prods/silver-items/sindoor-dani/sindoor-dani (3).jpg', '/prods/silver-items/sindoor-dani/sindoor-dani (4).jpg', '/prods/silver-items/sindoor-dani/sindoor-dani (5).jpg'],
    description: 'Stunning Silver Sindoor Dani',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '41',
    name: 'Star Deepak',
    category: 'silver-items',
    price: 125000,
    images: ['/prods/silver-items/Star-deepak/star-deepak (1).jpg', '/prods/silver-items/Star-deepak/star-deepak (2).jpg', '/prods/silver-items/Star-deepak/star-deepak (3).jpg', '/prods/silver-items/Star-deepak/star-deepak (4).jpg',],
    description: 'Stunning Silver Star Deepak',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '42',
    name: 'Suaa Pinjra',
    category: 'silver-items',
    price: 125000,
    images: ['/prods/silver-items/suaa-pinjra/sua-pinjara (1).jpg', '/prods/silver-items/suaa-pinjra/sua-pinjara (2).jpg', '/prods/silver-items/suaa-pinjra/sua-pinjara (3).jpg',],
    description: 'Stunning Silver Suaa Pinjra',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '43',
    name: 'Thos Murti',
    category: 'silver-items',
    price: 125000,
    images: ['/prods/silver-items/thos-moorti/thos-moorti (1).jpg', '/prods/silver-items/thos-moorti/thos-moorti (2).jpg', '/prods/silver-items/thos-moorti/thos-moorti (3).jpg', '/prods/silver-items/thos-moorti/thos-moorti (4).jpg',],
    description: 'Stunning Silver Thos Murti',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '44',
    name: 'Tulsi Gamla',
    category: 'silver-items',
    price: 125000,
    images: ['/prods/silver-items/tulsi-gamla/tulsi-gamla (1).jpg', '/prods/silver-items/tulsi-gamla/tulsi-gamla (2).jpg', '/prods/silver-items/tulsi-gamla/tulsi-gamla (3).jpg', '/prods/silver-items/tulsi-gamla/tulsi-gamla (4).jpg', '/prods/silver-items/tulsi-gamla/tulsi-gamla (5).jpg', '/prods/silver-items/tulsi-gamla/tulsi-gamla (6).jpg', '/prods/silver-items/tulsi-gamla/tulsi-gamla (7).jpg', '/prods/silver-items/tulsi-gamla/tulsi-gamla (8).jpg', '/prods/silver-items/tulsi-gamla/tulsi-gamla (9).jpg', '/prods/silver-items/tulsi-gamla/tulsi-gamla (10).jpg', '/prods/silver-items/tulsi-gamla/tulsi-gamla (11).jpg', '/prods/silver-items/tulsi-gamla/tulsi-gamla (12).jpg', '/prods/silver-items/tulsi-gamla/tulsi-gamla (13).jpg', '/prods/silver-items/tulsi-gamla/tulsi-gamla (14).jpg',],
    description: 'Stunning Silver Tulsi Gamla',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '45',
    name: 'Two Side Dibbi',
    category: 'silver-items',
    price: 125000,
    images: ['/prods/silver-items/two-side-dibbi/two-side-dibbi (1).jpg', '/prods/silver-items/two-side-dibbi/two-side-dibbi (2).jpg', '/prods/silver-items/two-side-dibbi/two-side-dibbi (3).jpg', '/prods/silver-items/two-side-dibbi/two-side-dibbi (4).jpg', '/prods/silver-items/two-side-dibbi/two-side-dibbi (5).jpg', '/prods/silver-items/two-side-dibbi/two-side-dibbi (6).jpg', '/prods/silver-items/two-side-dibbi/two-side-dibbi (7).jpg', '/prods/silver-items/two-side-dibbi/two-side-dibbi (8).jpg', '/prods/silver-items/two-side-dibbi/two-side-dibbi (9).jpg'],
    description: 'Stunning Silver Tulsi Gamla',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '1',
    name: 'Laddu Gopal Balti',
    category: 'laddu-gopal-items',
    price: 125000,
    images: ['/prods/laddu-gopal-items/laddu-gopal-balti/laddu-gopal-balti (1).jpg', '/prods/laddu-gopal-items/laddu-gopal-balti/laddu-gopal-balti (2).jpg', '/prods/laddu-gopal-items/laddu-gopal-balti/laddu-gopal-balti (3).jpg', '/prods/laddu-gopal-items/laddu-gopal-balti/laddu-gopal-balti (4).jpg', '/prods/laddu-gopal-items/laddu-gopal-balti/laddu-gopal-balti (5).jpg'],
    description: 'Stunning Laddu Gopal Balti',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '2',
    name: 'Laddu Gopal Balti Pichkari',
    category: 'laddu-gopal-items',
    price: 125000,
    images: ['/prods/laddu-gopal-items/laddu-gopal-balti-pichkari/laddu-gopal-balti-pichkari (1).jpg', '/prods/laddu-gopal-items/laddu-gopal-balti-pichkari/laddu-gopal-balti-pichkari (2).jpg', '/prods/laddu-gopal-items/laddu-gopal-balti-pichkari/laddu-gopal-balti-pichkari (3).jpg', '/prods/laddu-gopal-items/laddu-gopal-balti-pichkari/laddu-gopal-balti-pichkari (4).jpg', '/prods/laddu-gopal-items/laddu-gopal-balti-pichkari/laddu-gopal-balti-pichkari (5).jpg',],
    description: 'Stunning Laddu Gopal Balti Pichkari',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '3',
    name: 'Laddu Gopal Bansuri',
    category: 'laddu-gopal-items',
    price: 125000,
    images: ['/prods/laddu-gopal-items/laddu-gopal-bansuri/laddu-gopal-bansuri (1).jpg', '/prods/laddu-gopal-items/laddu-gopal-bansuri/laddu-gopal-bansuri (2).jpg', '/prods/laddu-gopal-items/laddu-gopal-bansuri/laddu-gopal-bansuri (3).jpg', '/prods/laddu-gopal-items/laddu-gopal-bansuri/laddu-gopal-bansuri (4).jpg', '/prods/laddu-gopal-items/laddu-gopal-bansuri/laddu-gopal-bansuri (5).jpg', '/prods/laddu-gopal-items/laddu-gopal-bansuri/laddu-gopal-bansuri (6).jpg', '/prods/laddu-gopal-items/laddu-gopal-bansuri/laddu-gopal-bansuri (7).jpg', '/prods/laddu-gopal-items/laddu-gopal-bansuri/laddu-gopal-bansuri (8).jpg', '/prods/laddu-gopal-items/laddu-gopal-bansuri/laddu-gopal-bansuri (9).jpg', '/prods/laddu-gopal-items/laddu-gopal-bansuri/laddu-gopal-bansuri (10).jpg', '/prods/laddu-gopal-items/laddu-gopal-bansuri/laddu-gopal-bansuri (11).jpg', '/prods/laddu-gopal-items/laddu-gopal-bansuri/laddu-gopal-bansuri (12).jpg', '/prods/laddu-gopal-items/laddu-gopal-bansuri/laddu-gopal-bansuri (13).jpg',],
    description: 'Stunning Laddu Gopal Bansuri',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '4',
    name: 'Laddu Gopal Hath Kada',
    category: 'laddu-gopal-items',
    price: 125000,
    images: ['/prods/laddu-gopal-items/laddu-gopal-hath-kada/laddu-gopal-hath-kada (1).jpg', '/prods/laddu-gopal-items/laddu-gopal-hath-kada/laddu-gopal-hath-kada (2).jpg', '/prods/laddu-gopal-items/laddu-gopal-hath-kada/laddu-gopal-hath-kada (3).jpg', '/prods/laddu-gopal-items/laddu-gopal-hath-kada/laddu-gopal-hath-kada (4).jpg',],
    description: 'Stunning Laddu Gopal Hath Kada',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '5',
    name: 'Laddu Gopal Jhula',
    category: 'laddu-gopal-items',
    price: 125000,
    images: ['/prods/laddu-gopal-items/laddu-gopal-jhula/laddu-gopal-jhula (1).jpg', '/prods/laddu-gopal-items/laddu-gopal-jhula/laddu-gopal-jhula (2).jpg', '/prods/laddu-gopal-items/laddu-gopal-jhula/laddu-gopal-jhula (3).jpg', '/prods/laddu-gopal-items/laddu-gopal-jhula/laddu-gopal-jhula (4).jpg', '/prods/laddu-gopal-items/laddu-gopal-jhula/laddu-gopal-jhula (5).jpg', '/prods/laddu-gopal-items/laddu-gopal-jhula/laddu-gopal-jhula (6).jpg', '/prods/laddu-gopal-items/laddu-gopal-jhula/laddu-gopal-jhula (7).jpg', '/prods/laddu-gopal-items/laddu-gopal-jhula/laddu-gopal-jhula (8).jpg'],
    description: 'Stunning Laddu Gopal Jhula',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '6',
    name: 'Laddu Gopal Makan',
    category: 'laddu-gopal-items',
    price: 125000,
    images: ['/prods/laddu-gopal-items/laddu-gopal-makan/laddu-gopal-makan (1).jpg', '/prods/laddu-gopal-items/laddu-gopal-makan/laddu-gopal-makan (2).jpg', '/prods/laddu-gopal-items/laddu-gopal-makan/laddu-gopal-makan (3).jpg', '/prods/laddu-gopal-items/laddu-gopal-makan/laddu-gopal-makan (4).jpg'],
    description: 'Stunning Laddu Gopal Makan',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '7',
    name: 'Laddu Gopal Mathdi',
    category: 'laddu-gopal-items',
    price: 125000,
    images: ['/prods/laddu-gopal-items/laddu-gopal-mathdi/laddu-gopal-mathdi (1).jpg', '/prods/laddu-gopal-items/laddu-gopal-mathdi/laddu-gopal-mathdi (2).jpg'],
    description: 'Stunning Laddu Gopal Mathdi',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '8',
    name: 'Laddu Gopal per Kadiya',
    category: 'laddu-gopal-items',
    price: 125000,
    images: ['/prods/laddu-gopal-items/laddu-gopal-pair-kadiya/laddu-gopal-pair-kadiya (1).jpg', '/prods/laddu-gopal-items/laddu-gopal-pair-kadiya/laddu-gopal-pair-kadiya (2).jpg'],
    description: 'Stunning Laddu Gopal Per Kadiya',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '9',
    name: 'Laddu Gopal Pankhi',
    category: 'laddu-gopal-items',
    price: 125000,
    images: ['/prods/laddu-gopal-items/laddu-gopal-pankhi/laddu-gopal-pankhi (1).jpg', '/prods/laddu-gopal-items/laddu-gopal-pankhi/laddu-gopal-pankhi (2).jpg', '/prods/laddu-gopal-items/laddu-gopal-pankhi/laddu-gopal-pankhi (3).jpg'],
    description: 'Stunning Laddu Gopal Per Kadiya',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '10',
    name: 'Laddu Gopal Sinhasan',
    category: 'laddu-gopal-items',
    price: 125000,
    images: ['/prods/laddu-gopal-items/laddu-gopal-sinhasan/laddu-gopal-sinhasan (1).jpg', '/prods/laddu-gopal-items/laddu-gopal-sinhasan/laddu-gopal-sinhasan (2).jpg', '/prods/laddu-gopal-items/laddu-gopal-sinhasan/laddu-gopal-sinhasan (3).jpg', '/prods/laddu-gopal-items/laddu-gopal-sinhasan/laddu-gopal-sinhasan (4).jpg', '/prods/laddu-gopal-items/laddu-gopal-sinhasan/laddu-gopal-sinhasan (5).jpg', '/prods/laddu-gopal-items/laddu-gopal-sinhasan/laddu-gopal-sinhasan (6).jpg', '/prods/laddu-gopal-items/laddu-gopal-sinhasan/laddu-gopal-sinhasan (7).jpg',],
    description: 'Stunning Laddu Gopal Sinhasan',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '11',
    name: 'Laddu Gopal Tippad',
    category: 'laddu-gopal-items',
    price: 125000,
    images: ['/prods/laddu-gopal-items/laddu-gopal-tippad/laddu-gopal-tippad (1).jpg', '/prods/laddu-gopal-items/laddu-gopal-tippad/laddu-gopal-tippad (2).jpg'],
    description: 'Stunning Laddu Gopal Sinhasan',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  // Add more sample products as needed
];

export const contactInfo: ContactInfo = {
  phone: '+91 9667177704',
  whatsapp: '6377209425 ',
  email: 'info@priyanshjewellers.com',
  address: 'Priyansh Jewellers, Sona Patti, Naya Bazar, Sujangarh 331507',
  hours: {
    weekdays: '10:00 AM - 8:00 PM',
    weekends: '10:00 AM - 9:00 PM',
  },
};

export const testimonials = [
  {
    id: '1',
    name: 'Priya Sharma',
    text: 'Beautiful jewelry with excellent craftsmanship. The gold quality is outstanding and the designs are unique.',
    rating: 5,
    location: 'Raipur',
  },
  {
    id: '2',
    name: 'Raj Patel',
    text: 'Trusted jeweller with transparent pricing. Bought my wedding rings here and couldn\'t be happier.',
    rating: 5,
    location: 'Durg',
  },
  {
    id: '3',
    name: 'Anita Gupta',
    text: 'Excellent customer service and wide variety of traditional designs. Highly recommended for special occasions.',
    rating: 5,
    location: 'Bhilai',
  },
];