import { Category, Product, Service, ContactInfo } from '@/types/jewelry';

export const categories: Category[] = [
  {
    id: '1',
    name: 'Gold Rings',
    slug: 'gold-rings',
    description: 'Elegant gold rings for every occasion',
    image: 'https://images.pexels.com/photos/30396670/pexels-photo-30396670.jpeg',
    productCount: 24,
  },
  {
    id: '2',
    name: 'Bracelets',
    slug: 'bracelets',
    description: 'Beautiful gold and diamond bracelets',
    image: 'https://i.pinimg.com/1200x/70/70/c0/7070c038191ca0b0efff96531bcb9604.jpg',
    productCount: 18,
  },
  {
    id: '3',
    name: 'Earrings',
    slug: 'earrings',
    description: 'Traditional and modern earring designs',
    image: 'https://i.pinimg.com/736x/7a/2f/df/7a2fdf103b96d1340e1774f9bb0d9228.jpg',
    productCount: 32,
  },
  {
    id: '4',
    name: 'Necklaces',
    slug: 'necklaces',
    description: 'Stunning necklaces for special moments',
    image: 'https://i.pinimg.com/1200x/7a/0c/60/7a0c607c683ac70fd73d650e2634b928.jpg',
    productCount: 28,
  },
  {
    id: '5',
    name: 'Bangles',
    slug: 'bangles',
    description: 'Traditional gold bangles and kadas',
    image: 'https://i.pinimg.com/1200x/07/45/72/074572b8951b853038e1fe6ef9f81cf1.jpg',
    productCount: 22,
  },
  {
    id: '6',
    name: 'Pendants',
    slug: 'pendants',
    description: 'Exquisite gold and diamond pendants',
    image: 'https://i.pinimg.com/1200x/72/f7/74/72f7743732fa5544b8a253a5c495965f.jpg',
    productCount: 16,
  },
  {
    id: '7',
    name: 'Silver Unique Items',
    slug: 'silver-items',
    description: 'Unique and exquisite silver items',
    image: '/prods/silver-items/charan-paduka/charan-paduka (1).jpg',
    productCount: 43,
  },
  {
    id: '8',
    name: 'Laddu Gopal Items',
    slug: 'laddu-gopal-items',
    description: 'Unique and exquisite laddu gopal items',
    image: '/prods/laddu-gopal-items/laddu-gopal-balti/laddu-gopal-balti (1).jpg',
    productCount: 11,
  },
  {
    id: '9',
    name: 'Silver Necklaces',
    slug: 'silver-necklaces',
    description: 'Diamond simulant, beads, antique polish, traditional necklaces',
    image: 'https://i.pinimg.com/736x/c9/38/4f/c9384f8f8a817372f5b84de2d9440986.jpg',
    productCount: 12,
  },
  {
    id: '10',
    name: 'Silver Pendants',
    slug: 'silver-pendants',
    description: 'Religious, meenakari, alphabet, kids, tabiz, pearl pendants',
    image: 'https://i.pinimg.com/736x/e7/c9/50/e7c9501e8613b6622e05f76a201ff676.jpg',
    productCount: 16,
  },
  {
    id: '11',
    name: 'Silver Earrings',
    slug: 'silver-earrings',
    description: 'Jhumka, Traditional, Antique, Simulant, Chandbali, Studs',
    image: 'https://i.pinimg.com/736x/26/b2/18/26b2188518bf62b77f3fdf33266eae08.jpg',
    productCount: 8,
  },
  {
    id: '12',
    name: 'Silver Bangles / Bracelets',
    slug: 'silver-bangles-bracelets',
    description: 'Gents, Female, Plain, beads, Evil-eye, Kada styles',
    image: 'https://i.pinimg.com/1200x/48/c9/8d/48c98d89c14c6d60040709b42286832b.jpg',
    productCount: 10,
  },
  {
    id: '13',
    name: 'Silver Rings',
    slug: 'silver-rings',
    description: 'Meenakari, simulant, engraved, bands, antique, premium',
    image: 'https://i.pinimg.com/1200x/77/1f/62/771f62920b29e49446b8f71c798f3f07.jpg',
    productCount: 10,
  },
  {
    id: '14',
    name: 'Silver Anklets (Payal)',
    slug: 'silver-anklets',
    description: 'Handmade, machine-made, daily wear, beads and more',
    image: 'https://i.pinimg.com/1200x/9a/1e/fa/9a1efa5764d9706166c1a311fe423b31.jpg',
    productCount: 10,
  },
  {
    id: '15',
    name: 'Silver Toe Rings',
    slug: 'silver-toe-rings',
    description: 'Plain, engraved, meenakari, diamond simulant',
    image: 'https://i.pinimg.com/736x/10/f8/a3/10f8a3d65737cbe7b093bd8c0c656653.jpg',
    productCount: 6,
  },
  {
    id: '16',
    name: 'Silver Waistbands (Kamarbandh)',
    slug: 'silver-waistbands',
    description: 'Traditional, Bridal, Machine-Made',
    image: 'https://i.pinimg.com/736x/69/4d/ab/694dab8d53299dcb3eb6b10f803c5900.jpg',
    productCount: 6,
  },
  {
    id: '17',
    name: 'Silver Hair Accessories',
    slug: 'silver-hair-accessories',
    description: 'Hair Pins, Braid Band, Silver Comb',
    image: 'https://i.pinimg.com/736x/e9/47/18/e9471896b7c33d01984bb94441b81ac0.jpg',
    productCount: 6,
  },
  {
    id: '18',
    name: 'Silver Chains',
    slug: 'silver-chains',
    description: 'Daily wear, Antique, Religious malas',
    image: 'https://i.pinimg.com/736x/93/2c/b5/932cb5f1c96079515ea7fb1c9f2a8946.jpg',
    productCount: 8,
  },
  {
    id: '19',
    name: 'Silver Utensils & Articles',
    slug: 'silver-utensils-articles',
    description: 'Utensils, decorative items, frames and more',
    image: 'https://i.pinimg.com/1200x/32/93/56/329356dbbade5399d621178fb5701d8d.jpg',
    productCount: 12,
  },
  {
    id: '20',
    name: 'Silver Rajputi Jewellery',
    slug: 'silver-rajputi',
    description: 'Festival & Wedding Sets',
    image: 'https://i.pinimg.com/1200x/b0/2a/81/b02a81b1c5332ad4708e836ee4d2b6cb.jpg',
    productCount: 4,
  },
  {
    id: '21',
    name: 'Silver Pujan Items',
    slug: 'silver-pujan-items',
    description: 'Thakur Ji shringar, deepak, idols, yantras and more',
    image: 'https://i.pinimg.com/736x/6c/53/4b/6c534b7af7996f0ed6a5508d540eda29.jpg',
    productCount: 12,
  },
];

export const services: Service[] = [
  {
    id: '1',
    title: 'Digital Gold',
    description: 'Invest in 24k pure gold digitally with instant buying and selling',
    icon: 'smartphone',
    features: ['24k Pure Gold', 'Instant Transactions', 'Secure Storage', 'Real-time Rates'],
  },
  {
    id: '2',
    title: 'Gold SIP',
    description: 'Systematic Investment Plan for gold with flexible monthly payments',
    icon: 'trending-up',
    features: ['Monthly SIP', 'Flexible Amount', 'Long-term Growth', 'Tax Benefits'],
  },
  {
    id: '3',
    title: 'E-Gift Card',
    description: 'Perfect gift for your loved ones, redeemable across all jewelry',
    icon: 'gift',
    features: ['Instant Delivery', 'Custom Amount', 'No Expiry', 'Easy Redemption'],
  },
  {
    id: '4',
    title: 'Custom Jewelry',
    description: 'Design your own unique pieces with our expert craftsmen',
    icon: 'pen-tool',
    features: ['Personal Design', 'Expert Crafting', 'Premium Materials', 'Lifetime Service'],
  },
];

export const sampleProducts: Product[] = [
  {
    id: '1',
    name: 'Traditional Gold Ring',
    category: 'gold-rings',
    // price: 45000,
    // originalPrice: 48000,
    images: ['https://i.pinimg.com/736x/4d/60/d5/4d60d51bde90cc38869644973402a1b0.jpg'],
    description: 'Elegant 22k gold ring with intricate traditional design',
    material: '22k Gold',
    // weight: '8.5g',
    // purity: '916',
    inStock: true,
    featured: true,
  },
  // Minimal products per new category with tags for filters
  // Silver Necklaces
  {
    id: 'sn-1',
    name: 'Simulant Halo Necklace',
    category: 'silver-necklaces',
    // price: 3499, 
    images: ['https://i.pinimg.com/736x/39/12/e1/3912e18421a082415d562700634312d2.jpg'],
    description: 'Halo diamond simulant pendant', material: '925 Silver', inStock: true, featured: true, tags: ['diamond simulant']
  },
  {
    id: 'sn-2', name: 'Black Beads Mala', category: 'silver-necklaces',
    // price: 1999, 
    images: ['https://i.pinimg.com/1200x/51/5e/e7/515ee7c3a471871b299956ab1b974bc6.jpg'], description: 'Traditional black beads', material: '925 Silver + Beads', inStock: true, featured: false, tags: ['Beads Necklace']
  },
  {
    id: 'sn-3', name: 'Antique Temple Choker', category: 'silver-necklaces',
    //  price: 4299,
    images: ['https://i.pinimg.com/1200x/12/9d/87/129d87a4884ef90474ef736d9702eadc.jpg'], description: 'Antique polish temple motifs', material: '925 Silver', inStock: true, featured: false, tags: ['Antique Gold Polished']
  },
  {
    id: 'sn-4', name: 'Traditional Coin Mala', category: 'silver-necklaces',
    // price: 3199,
    images: ['https://i.pinimg.com/736x/52/ba/0c/52ba0c33257303672d405f13c4c1dc17.jpg'], description: 'Traditional coin discs', material: '925 Silver', inStock: true, featured: false, tags: ['Traditional']
  },

  // Silver Pendants
  {
    id: 'sp-1', name: 'Hanuman Ji Pendant', category: 'silver-pendants',
    // price: 1199, 
    images: ['https://i.pinimg.com/1200x/d8/a9/1b/d8a91bd5f80fca9e951ff6d327e8db32.jpg'], description: 'Religious symbol', material: '925 Silver', inStock: true, featured: true, tags: ['Religious Symbols', 'Hanuman ji']
  },
  {
    id: 'sp-2', name: 'Meenakari Flower Pendant', category: 'silver-pendants',
    // price: 1399, 
    images: ['https://i.pinimg.com/1200x/99/95/ce/9995ce07e0e6b9368d0474855f6152d4.jpg'], description: 'Colorful enamel work', material: '925 Silver + Enamel', inStock: true, featured: false, tags: ['Meenakari', 'Flower']
  },
  {
    id: 'sp-3', name: 'Alphabet A Pendant', category: 'silver-pendants',
    // price: 999, 
    images: ['https://i.pinimg.com/1200x/84/0c/db/840cdbb4c352d01304e162bd10d0043e.jpg'], description: 'Initial pendant', material: '925 Silver', inStock: true, featured: false, tags: ['Alphabatical']
  },
  {
    id: 'sp-4', name: 'Pearl Drop Pendant', category: 'silver-pendants',
    //  price: 1499,
    images: ['https://i.pinimg.com/1200x/83/fe/57/83fe57016fe6b5b01be21357bfe5a23d.jpg'], description: 'Elegant pearl drop', material: '925 Silver + Pearl', inStock: true, featured: false, tags: ['pearl']
  },

  // Silver Earrings
  {
    id: 'se-1', name: 'Traditional Jhumka', category: 'silver-earrings',
    // price: 1699,
    images: ['https://i.pinimg.com/1200x/11/12/a4/1112a46212544e44c9d303d61f133bbc.jpg'], description: 'Bell-shaped jhumka', material: '925 Silver', inStock: true, featured: true, tags: ['Jhumka', 'Traditional']
  },
  {
    id: 'se-2', name: 'Simulant Studs', category: 'silver-earrings',
    //  price: 999, 
    images: ['https://i.pinimg.com/736x/fe/a3/96/fea396d8788b56d5d8409697776a3d78.jpg'], description: 'Everyday studs', material: '925 Silver', inStock: true, featured: false, tags: ['Studs', 'diamond simulant']
  },
  {
    id: 'se-3', name: 'Oxidised Chandbali', category: 'silver-earrings',
    //  price: 1899,
    images: ['https://i.pinimg.com/736x/b0/fa/45/b0fa456e5c67c4a9aaaa3c1150e51232.jpg'], description: 'Half-moon style', material: '925 Silver', inStock: true, featured: false, tags: ['Chandbali', 'Antique']
  },

  // Silver Bangles / Bracelets
  {
    id: 'sbb-1', name: 'Gents Looped Kada', category: 'silver-bangles-bracelets',
    // price: 2499, 
    images: ['https://i.pinimg.com/736x/31/a7/1b/31a71b4087a5fabea5a896b345ae2cb4.jpg'], description: 'Looped kada', material: '925 Silver', inStock: true, featured: false, tags: ['Gents', 'Kadaa', 'Looped Kada']
  },
  {
    id: 'sbb-2', name: 'Evil-Eye Bracelet', category: 'silver-bangles-bracelets',
    // price: 1499, 
    images: ['https://i.pinimg.com/1200x/c8/2e/7b/c82e7bb9fd5c6bcc03592c86d3915b31.jpg'], description: 'Protection charm', material: '925 Silver', inStock: true, featured: false, tags: ['Evel-Eye']
  },
  {
    id: 'sbb-3', name: 'Black Beads Bracelet', category: 'silver-bangles-bracelets',
    // price: 1199, 
    images: ['https://i.pinimg.com/736x/ef/d1/9c/efd19c96fcc7c4787ae2cfb15c71640e.jpg'], description: 'Black beads', material: '925 Silver', inStock: true, featured: false, tags: ['beads', 'black beads']
  },

  // Silver Rings
  {
    id: 'sr-1', name: 'Meenakari Ring', category: 'silver-rings',
    // price: 1299, 
    images: ['https://i.pinimg.com/1200x/5c/90/c6/5c90c63121bb0f34fb977773e69c3951.jpg'], description: 'Enamel finish', material: '925 Silver', inStock: true, featured: false, tags: ['Meenakari']
  },
  {
    id: 'sr-2', name: 'Plain Band', category: 'silver-rings',
    //  price: 899, 
    images: ['https://i.pinimg.com/1200x/94/63/36/946336dce0c88a122b5b1e54ea35180f.jpg'], description: 'Classic band', material: '925 Silver', inStock: true, featured: false, tags: ['Plain Bands', 'plain']
  },
  {
    id: 'sr-3', name: 'Simulant Halo Ring', category: 'silver-rings',
    // price: 1599,
    images: ['https://i.pinimg.com/1200x/e5/fe/b5/e5feb570df136cd530e2b9b97d3c61b3.jpg'], description: 'Halo simulant', material: '925 Silver', inStock: true, featured: true, tags: ['diamond simulant']
  },

  // Silver Anklets (Payal)
  {
    id: 'sa-1', name: 'Handmade Payal', category: 'silver-anklets',
    // price: 1999,
    images: ['https://i.pinimg.com/1200x/de/bc/0c/debc0c001373c29c00bfb5cad65fe905.jpg'], description: 'Handcrafted', material: '925 Silver', inStock: true, featured: false, tags: ['Handmade', 'Traditional']
  },
  {
    id: 'sa-2', name: 'Machine-made Payal', category: 'silver-anklets',
    // price: 1299,
    images: ['https://i.pinimg.com/1200x/58/d9/94/58d9944fca66657398c0e1a4ea3e5b49.jpg'], description: 'Durable links', material: '925 Silver', inStock: true, featured: false, tags: ['Machine-made', 'Daily wear']
  },

  // Silver Toe Rings
  {
    id: 'st-1', name: 'Plain Toe Ring', category: 'silver-toe-rings',
    // price: 399,
    images: ['https://i.pinimg.com/736x/b7/d6/1c/b7d61c14614e713b6461ca4d6ea1a79a.jpg'], description: 'Everyday ring', material: '925 Silver', inStock: true, featured: false, tags: ['Plain']
  },
  {
    id: 'st-2', name: 'Simulant Toe Ring', category: 'silver-toe-rings',
    // price: 499,
    images: ['https://i.pinimg.com/736x/cc/fd/f1/ccfdf11752849e6b5db60530954c7604.jpg'], description: 'Sparkling simulant', material: '925 Silver', inStock: true, featured: false, tags: ['diamond simulant']
  },

  // Silver Waistbands (Kamarbandh)
  {
    id: 'sw-1', name: 'Traditional Kamarbandh', category: 'silver-waistbands',
    // price: 3499,
    images: ['https://i.pinimg.com/1200x/36/b7/1b/36b71b89608607b56d5d9b66a10d5301.jpg'], description: 'Traditional motifs', material: '925 Silver', inStock: true, featured: false, tags: ['Traditional']
  },
  {
    id: 'sw-2', name: 'Bridal Kamarbandh', category: 'silver-waistbands',
    // price: 4999, 
    images: ['https://i.pinimg.com/736x/06/17/9d/06179d19ddc796c83194b9501af048e5.jpg'], description: 'Bridal style', material: '925 Silver', inStock: true, featured: true, tags: ['Bridal']
  },

  // Silver Hair Accessories
  {
    id: 'sha-1', name: 'Silver Hair Pin', category: 'silver-hair-accessories',
    // price: 599, 
    images: ['https://i.pinimg.com/736x/19/68/17/196817cdab639e7c5b12edf1ab32c785.jpg'], description: 'Elegant pin', material: '925 Silver', inStock: true, featured: false, tags: ['Hair Pins']
  },
  {
    id: 'sha-2', name: 'Braid Band', category: 'silver-hair-accessories',
    // price: 999,
    images: ['https://i.pinimg.com/1200x/2b/9c/0f/2b9c0fbe77e30cb23a80b52d9efc59cd.jpg'], description: 'Decor braid band', material: '925 Silver', inStock: true, featured: false, tags: ['Braid Band']
  },

  // Silver Chains
  {
    id: 'sc-1', name: 'Daily Wear Chain', category: 'silver-chains',
    // price: 1199,
    images: ['https://i.pinimg.com/736x/dc/2a/78/dc2a7836be534b359e609196b1b4bdb3.jpg'], description: 'Light chain', material: '925 Silver', inStock: true, featured: false, tags: ['Daily Wear']
  },
  {
    id: 'sc-2', name: 'Rudraksh Mala', category: 'silver-chains',
    // price: 1499,
    images: ['https://i.pinimg.com/736x/72/23/bc/7223bc6a0e0650fb2f2e456a5952e371.jpg'], description: 'Religious mala', material: '925 Silver + Rudraksh', inStock: true, featured: false, tags: ['Religious', 'Rudraksh Mala']
  },

  // Silver Utensils & Articles
  {
    id: 'sua-1', name: 'Puja Thali Set', category: 'silver-utensils-articles',
    // price: 8999,
    images: ['https://i.pinimg.com/1200x/3d/ca/f1/3dcaf1f90dc9db992085e2afccbdad33.jpg'], description: 'Thali with bowls', material: 'Silver Plated', inStock: true, featured: true, tags: ['Utensils', 'Puja Thali']
  },
  {
    id: 'sua-2', name: 'Whiskey Flask', category: 'silver-utensils-articles',
    // price: 4999,
    images: ['https://i.pinimg.com/736x/e1/3b/aa/e13baad0b16453ddd2756395c728f491.jpg'], description: 'Coated flask', material: 'Coated Silver', inStock: true, featured: false, tags: ['Decorative Items', 'Wihskey Flask']
  },

  // Silver Rajputi Jewellery
  {
    id: 'srj-1', name: 'Rajputi Wedding Set', category: 'silver-rajputi',
    // price: 12999,
    images: ['https://i.pinimg.com/736x/e8/9b/e7/e89be7afcbe52781fa528f095bfef68b.jpg'], description: 'Wedding set', material: '925 Silver', inStock: true, featured: true, tags: ['Festival & Wedding Sets']
  },
  {
    id: 'srj-2', name: 'Rajputi Festival Set', category: 'silver-rajputi',
    // price: 10999,
    images: ['https://i.pinimg.com/736x/8d/f0/94/8df094e386e61daed2c21ec73da708ad.jpg'], description: 'Festival set', material: '925 Silver', inStock: true, featured: false, tags: ['Festival & Wedding Sets']
  },

  // Silver Pujan Items
  {
    id: 'spi-1', name: 'Simple Deepak', category: 'silver-pujan-items',
    // price: 799,
    images: ['https://i.pinimg.com/736x/12/75/31/12753150d8d088497805b835afa1197f.jpg'], description: 'Everyday diya', material: '925 Silver', inStock: true, featured: false, tags: ['deepak', 'Simple Dipak']
  },
  {
    id: 'spi-2', name: 'Shri Ganesha Idol', category: 'silver-pujan-items',
    // price: 2999,
    images: ['https://i.pinimg.com/736x/5e/4b/4d/5e4b4dbc9e6919a5c096900828af840a.jpg'], description: 'Ganesha idol', material: 'Silver Plated', inStock: true, featured: false, tags: ['idols', 'Shri Ganesha Idol']
  },
  {
    id: '2',
    name: 'Diamond Bracelet',
    category: 'bracelets',
    // price: 125000,
    images: ['https://images.pexels.com/photos/1454191/pexels-photo-1454191.jpeg?auto=compress&cs=tinysrgb&w=600'],
    description: 'Stunning diamond bracelet with 18k gold setting',
    material: '18k Gold + Diamonds',
    // weight: '12.3g',
    // purity: '750',
    inStock: true,
    featured: true,
  },
  {
    id: '3',
    name: 'Charan Paduka',
    category: 'silver-items',
    // price: 125000,
    images: ['/prods/silver-items/charan-paduka/charan-paduka (1).jpg', '/prods/silver-items/charan-paduka/charan-paduka (2).jpg', '/prods/silver-items/charan-paduka/charan-paduka (3).jpg', '/prods/silver-items/charan-paduka/charan-paduka (4).jpg', '/prods/silver-items/charan-paduka/charan-paduka (5).jpg', '/prods/silver-items/charan-paduka/charan-paduka (6).jpg', '/prods/silver-items/charan-paduka/charan-paduka (7).jpg', '/prods/silver-items/charan-paduka/charan-paduka (8).jpg', '/prods/silver-items/charan-paduka/charan-paduka (9).jpg', '/prods/silver-items/charan-paduka/charan-paduka (10).jpg', '/prods/silver-items/charan-paduka/charan-paduka (11).jpg', '/prods/silver-items/charan-paduka/charan-paduka (12).jpg', '/prods/silver-items/charan-paduka/charan-paduka (13).jpg'],
    description: 'Stunning Silver Charan Paduka',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '4',
    name: 'Agarbatti Stand',
    category: 'silver-items',
    // price: 125000,
    images: ['/prods/silver-items/agarbatti-stand/agarbatti-stand (1).jpg', '/prods/silver-items/agarbatti-stand/agarbatti-stand (2).jpg', '/prods/silver-items/agarbatti-stand/agarbatti-stand (3).jpg', '/prods/silver-items/agarbatti-stand/agarbatti-stand (4).jpg', '/prods/silver-items/agarbatti-stand/agarbatti-stand (5).jpg', '/prods/silver-items/agarbatti-stand/agarbatti-stand (6).jpg', '/prods/silver-items/agarbatti-stand/agarbatti-stand (7).jpg', '/prods/silver-items/agarbatti-stand/agarbatti-stand (8).jpg'],
    description: 'Stunning Silver Agarbatti Stand',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '5',
    name: 'Bahumukhi Deepak',
    category: 'silver-items',
    // price: 125000,
    images: ['/prods/silver-items/bahumukhi-deepak/bahumukhi-deepak (1).jpg', '/prods/silver-items/bahumukhi-deepak/bahumukhi-deepak (2).jpg', '/prods/silver-items/bahumukhi-deepak/bahumukhi-deepak (3).jpg', '/prods/silver-items/bahumukhi-deepak/bahumukhi-deepak (4).jpg'],
    description: 'Stunning Silver Bahumukhi Deepak',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '6',
    name: 'Chaaku',
    category: 'silver-items',
    // price: 125000,
    images: ['/prods/silver-items/chaaku/chaaku (1).jpg', '/prods/silver-items/chaaku/chaaku (2).jpg', '/prods/silver-items/chaaku/chaaku (3).jpg'],
    description: 'Stunning Silver Chaaku',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '7',
    name: 'Chanwar(only hattha)',
    category: 'silver-items',
    // price: 125000,
    images: ['/prods/silver-items/chanwar-only-hattha/chaanvar(only hattha) (1).jpg', '/prods/silver-items/chanwar-only-hattha/chaanvar(only hattha) (2).jpg', '/prods/silver-items/chanwar-only-hattha/chaanvar(only hattha) (3).jpg'],
    description: 'Stunning Silver Chanwar(only hattha)',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '8',
    name: 'Kachhua Chaupada',
    category: 'silver-items',
    // price: 125000,
    images: ['/prods/silver-items/chaupda/kachhua-chaupda (1).jpg', '/prods/silver-items/chaupda/kachhua-chaupda (2).jpg'],
    description: 'Stunning Silver KachhuaChaupada',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '9',
    name: 'Mor Chaupada',
    category: 'silver-items',
    // price: 125000,
    images: ['/prods/silver-items/chaupda/mor-chaupda (1).jpg', '/prods/silver-items/chaupda/mor-chaupda (2).jpg'],
    description: 'Stunning Silver Mor Chaupada',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '10',
    name: 'Chilam',
    category: 'silver-items',
    // price: 125000,
    images: ['/prods/silver-items/chillam/chillam (1).jpg', '/prods/silver-items/chillam/chillam (2).jpg', '/prods/silver-items/chillam/chillam (3).jpg', '/prods/silver-items/chillam/chillam (4).jpg', "/prods/silver-items/chillam/chillam (5).jpg"],
    description: 'Stunning Silver Chilam',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '11',
    name: 'Damru Trisul',
    category: 'silver-items',
    // price: 125000,
    images: ['/prods/silver-items/damru-trisul/damru-trisul (1).jpg', '/prods/silver-items/damru-trisul/damru-trisul (2).jpg'],
    description: 'Stunning Silver Damru Trisul',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '12',
    name: 'Deepak Stand',
    category: 'silver-items',
    // price: 125000,
    images: ['/prods/silver-items/deepak-stand/deepak-stand (1).jpg', '/prods/silver-items/deepak-stand/deepak-stand (2).jpg'],
    description: 'Stunning Silver Deepak Stand',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '13',
    name: 'Dibbi',
    category: 'silver-items',
    // price: 125000,
    images: ['/prods/silver-items/dibbi/dibbi (1).jpg', '/prods/silver-items/dibbi/dibbi (2).jpg', "/prods/silver-items/dibbi/dibbi (3).jpg", "/prods/silver-items/dibbi/dibbi (4).jpg", "/prods/silver-items/dibbi/dibbi (5).jpg", "/prods/silver-items/dibbi/dibbi (6).jpg", "/prods/silver-items/dibbi/dibbi (7).jpg", "/prods/silver-items/dibbi/dibbi (8).jpg", "/prods/silver-items/dibbi/dibbi (9).jpg", "/prods/silver-items/dibbi/dibbi (10).jpg", "/prods/silver-items/dibbi/dibbi (11).jpg", "/prods/silver-items/dibbi/dibbi (12).jpg", "/prods/silver-items/dibbi/dibbi (13).jpg", "/prods/silver-items/dibbi/dibbi (14).jpg", "/prods/silver-items/dibbi/dibbi (15).jpg", "/prods/silver-items/dibbi/dibbi (16).jpg"],
    description: 'Stunning Silver Dibbi',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '14',
    name: 'Firkali',
    category: 'silver-items',
    // price: 125000,
    images: ['/prods/silver-items/firkali/firkli (1).jpg', '/prods/silver-items/firkali/firkli (2).jpg', "/prods/silver-items/firkali/firkli (3).jpg", "/prods/silver-items/firkali/firkli (4).jpg", "/prods/silver-items/firkali/firkli (5).jpg", "/prods/silver-items/firkali/firkli (6).jpg", "/prods/silver-items/firkali/firkli (7).jpg", "/prods/silver-items/firkali/firkli (8).jpg", "/prods/silver-items/firkali/firkli (9).jpg"],
    description: 'Stunning Silver Firkali',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '15',
    name: 'Gaaya',
    category: 'silver-items',
    // price: 125000,
    images: ['/prods/silver-items/gaay/gaay (1).jpg', '/prods/silver-items/gaay/gaay (2).jpg', "/prods/silver-items/gaay/gaay (3).jpg", "/prods/silver-items/gaay/gaay (4).jpg", "/prods/silver-items/gaay/gaay (5).jpg", "/prods/silver-items/gaay/gaay (6).jpg", "/prods/silver-items/gaay/gaay (7).jpg", "/prods/silver-items/gaay/gaay (8).jpg", "/prods/silver-items/gaay/gaay (9).jpg", "/prods/silver-items/gaay/gaay (10).jpg", "/prods/silver-items/gaay/gaay (11).jpg", "/prods/silver-items/gaay/gaay (12).jpg", "/prods/silver-items/gaay/gaay (13).jpg", "/prods/silver-items/gaay/gaay (14).jpg", "/prods/silver-items/gaay/gaay (15).jpg", "/prods/silver-items/gaay/gaay (16).jpg"],
    description: 'Stunning Silver Gaaya',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '16',
    name: 'Ghatti',
    category: 'silver-items',
    // price: 125000,
    images: ['/prods/silver-items/ghatti/ghatti (1).jpg', '/prods/silver-items/ghatti/ghatti (2).jpg', "/prods/silver-items/ghatti/ghatti (3).jpg", "/prods/silver-items/ghatti/ghatti (4).jpg", "/prods/silver-items/ghatti/ghatti (5).jpg", "/prods/silver-items/ghatti/ghatti (6).jpg", "/prods/silver-items/ghatti/ghatti (7).jpg", "/prods/silver-items/ghatti/ghatti (8).jpg", "/prods/silver-items/ghatti/ghatti (9).jpg", "/prods/silver-items/ghatti/ghatti (10).jpg", "/prods/silver-items/ghatti/ghatti (11).jpg", "/prods/silver-items/ghatti/ghatti (12).jpg", "/prods/silver-items/ghatti/ghatti (13).jpg", "/prods/silver-items/ghatti/ghatti (14).jpg", "/prods/silver-items/ghatti/ghatti (15).jpg", "/prods/silver-items/ghatti/ghatti (16).jpg"],
    description: 'Stunning Silver Ghatti',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '18',
    name: 'Chhota Gada',
    category: 'silver-items',
    // price: 125000,
    images: ['/prods/silver-items/ghota-gada/gada-ghota (1).jpg', '/prods/silver-items/ghota-gada/gada-ghota (2).jpg', "/prods/silver-items/ghota-gada/gada-ghota (3).jpg", "/prods/silver-items/ghota-gada/gada-ghota (4).jpg", "/prods/silver-items/ghota-gada/gada-ghota (5).jpg", "/prods/silver-items/ghota-gada/gada-ghota (6).jpg", "/prods/silver-items/ghota-gada/gada-ghota (7).jpg", "/prods/silver-items/ghota-gada/gada-ghota (8).jpg", "/prods/silver-items/ghota-gada/gada-ghota (9).jpg", "/prods/silver-items/ghota-gada/gada-ghota (10).jpg", "/prods/silver-items/ghota-gada/gada-ghota (11).jpg", "/prods/silver-items/ghota-gada/gada-ghota (12).jpg", "/prods/silver-items/ghota-gada/gada-ghota (13).jpg", "/prods/silver-items/ghota-gada/gada-ghota (14).jpg", "/prods/silver-items/ghota-gada/gada-ghota (15).jpg", "/prods/silver-items/ghota-gada/gada-ghota (16).jpg", "/prods/silver-items/ghota-gada/gada-ghota (17).jpg", "/prods/silver-items/ghota-gada/gada-ghota (18).jpg", "/prods/silver-items/ghota-gada/gada-ghota (19).jpg", "/prods/silver-items/ghota-gada/gada-ghota (20).jpg", "/prods/silver-items/ghota-gada/gada-ghota (21).jpg"],
    description: 'Stunning Silver Chhota Gada',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '19',
    name: 'Handle Deepak',
    category: 'silver-items',
    // price: 125000,
    images: ['/prods/silver-items/handle-deepak/handle-deepak (1).jpg', '/prods/silver-items/handle-deepak/handle-deepak (2).jpg'],
    description: 'Stunning Silver Handle Deepak',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '20',
    name: 'Hollow Murti',
    category: 'silver-items',
    // price: 125000,
    images: ['/prods/silver-items/hollow-moorti/hollow-moorti (1).jpg', '/prods/silver-items/hollow-moorti/hollow-moorti (2).jpg', "/prods/silver-items/hollow-moorti/hollow-moorti (3).jpg", "/prods/silver-items/hollow-moorti/hollow-moorti (4).jpg", "/prods/silver-items/hollow-moorti/hollow-moorti (5).jpg", "/prods/silver-items/hollow-moorti/hollow-moorti (6).jpg", "/prods/silver-items/hollow-moorti/hollow-moorti (7).jpg", "/prods/silver-items/hollow-moorti/hollow-moorti (8).jpg", "/prods/silver-items/hollow-moorti/hollow-moorti (9).jpg"],
    description: 'Stunning Silver Hollow Murti',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '21',
    name: 'Hollow Stand Murti',
    category: 'silver-items',
    // price: 125000,
    images: ['/prods/silver-items/hollow-stand-moorti/hollow-stand-moorti (1).jpg', '/prods/silver-items/hollow-stand-moorti/hollow-stand-moorti (2).jpg', "/prods/silver-items/hollow-stand-moorti/hollow-stand-moorti (3).jpg", "/prods/silver-items/hollow-stand-moorti/hollow-stand-moorti (4).jpg", "/prods/silver-items/hollow-stand-moorti/hollow-stand-moorti (5).jpg", "/prods/silver-items/hollow-stand-moorti/hollow-stand-moorti (6).jpg", "/prods/silver-items/hollow-stand-moorti/hollow-stand-moorti (7).jpg", "/prods/silver-items/hollow-stand-moorti/hollow-stand-moorti (8).jpg"],
    description: 'Stunning Silver Hollow Stand Murti',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '22',
    name: 'Ittra Dani',
    category: 'silver-items',
    // price: 125000,
    images: ['/prods/silver-items/ittra-dani/ittra-daani (1).jpg', '/prods/silver-items/ittra-dani/ittra-daani (2).jpg', "/prods/silver-items/ittra-dani/ittra-daani (3).jpg"],
    description: 'Stunning Silver Ittra Dani',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '23',
    name: 'Ittra Favvara',
    category: 'silver-items',
    // price: 125000,
    images: ['/prods/silver-items/ittra-favvara/ittra-favvara (1).jpg', '/prods/silver-items/ittra-favvara/ittra-favvara (2).jpg', "/prods/silver-items/ittra-favvara/ittra-favvara (3).jpg", "/prods/silver-items/ittra-favvara/ittra-favvara (4).jpg"],
    description: 'Stunning Silver Ittra Favvara',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '24',
    name: 'Jaanvar',
    category: 'silver-items',
    // price: 125000,
    images: ['/prods/silver-items/jaanvar/jaanvar (1).jpg', '/prods/silver-items/jaanvar/jaanvar (2).jpg', "/prods/silver-items/jaanvar/jaanvar (3).jpg", "/prods/silver-items/jaanvar/jaanvar (4).jpg", "/prods/silver-items/jaanvar/jaanvar (5).jpg"],
    description: 'Stunning Silver Jaanvar',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '24',
    name: 'Jaanvar Meena',
    category: 'silver-items',
    // price: 125000,
    images: ['/prods/silver-items/janvar-meena/jaanvar-meena (1).jpg', '/prods/silver-items/janvar-meena/jaanvar-meena (2).jpg', "/prods/silver-items/janvar-meena/jaanvar-meena (3).jpg", "/prods/silver-items/janvar-meena/jaanvar-meena (4).jpg", "/prods/silver-items/janvar-meena/jaanvar-meena (5).jpg", "/prods/silver-items/janvar-meena/jaanvar-meena (6).jpg", "/prods/silver-items/janvar-meena/jaanvar-meena (7).jpg", "/prods/silver-items/janvar-meena/jaanvar-meena (8).jpg", "/prods/silver-items/janvar-meena/jaanvar-meena (9).jpg", "/prods/silver-items/janvar-meena/jaanvar-meena (10).jpg"],
    description: 'Stunning Silver Jaanvar Meena',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '25',
    name: 'Kalash',
    category: 'silver-items',
    // price: 125000,
    images: ['/prods/silver-items/kalash/kalash (1).jpg', '/prods/silver-items/kalash/kalash (2).jpg', "/prods/silver-items/kalash/kalash (3).jpg", "/prods/silver-items/kalash/kalash (4).jpg", "/prods/silver-items/kalash/kalash (5).jpg", "/prods/silver-items/kalash/kalash (6).jpg", "/prods/silver-items/kalash/kalash (7).jpg", "/prods/silver-items/kalash/kalash (8).jpg", "/prods/silver-items/kalash/kalash (9).jpg"],
    description: 'Stunning Silver Kalash',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '26',
    name: 'Khedi Dibbi',
    category: 'silver-items',
    // price: 125000,
    images: ['/prods/silver-items/khedi-dibbi/khedi-dibbi (1).jpg', '/prods/silver-items/khedi-dibbi/khedi-dibbi (2).jpg', "/prods/silver-items/khedi-dibbi/khedi-dibbi (3).jpg", "/prods/silver-items/khedi-dibbi/khedi-dibbi (4).jpg", "/prods/silver-items/khedi-dibbi/khedi-dibbi (5).jpg"],
    description: 'Stunning Silver Khedi Dibbi',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '27',
    name: 'Lakshmi Mata Deepak',
    category: 'silver-items',
    // price: 125000,
    images: ['/prods/silver-items/lakshmi-mata-deepak/lakshmi-mata-deepak (1).jpg', '/prods/silver-items/lakshmi-mata-deepak/lakshmi-mata-deepak (2).jpg', "/prods/silver-items/lakshmi-mata-deepak/lakshmi-mata-deepak (3).jpg", "/prods/silver-items/lakshmi-mata-deepak/lakshmi-mata-deepak (4).jpg", "/prods/silver-items/lakshmi-mata-deepak/lakshmi-mata-deepak (5).jpg", "/prods/silver-items/lakshmi-mata-deepak/lakshmi-mata-deepak (6).jpg", "/prods/silver-items/lakshmi-mata-deepak/lakshmi-mata-deepak (7).jpg"],
    description: 'Stunning Silver Lakshmi Mata Deepak',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '27',
    name: 'Mandir Ghanti',
    category: 'silver-items',
    // price: 125000,
    images: ['/prods/silver-items/mandir-ghanti/mandir-ghanti.jpg'],
    description: 'Stunning Silver Mandir Ghanti',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '28',
    name: 'Nada Pirohni',
    category: 'silver-items',
    // price: 125000,
    images: ['/prods/silver-items/nada-pirohni/nada-pirohdi (1).jpg', '/prods/silver-items/nada-pirohni/nada-pirohdi (2).jpg'],
    description: 'Stunning Silver Nada Pirohni',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '29',
    name: 'Nandi',
    category: 'silver-items',
    // price: 125000,
    images: ['/prods/silver-items/nandi/nandi (1).jpg', '/prods/silver-items/nandi/nandi (2).jpg'],
    description: 'Stunning Silver Nandi',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '30',
    name: 'Pakshi',
    category: 'silver-items',
    // price: 125000,
    images: ['/prods/silver-items/pakshi/pakkshi (1).jpg', '/prods/silver-items/pakshi/pakkshi (2).jpg', "/prods/silver-items/pakshi/pakkshi (3).jpg", "/prods/silver-items/pakshi/pakkshi (4).jpg", "/prods/silver-items/pakshi/pakkshi (5).jpg", "/prods/silver-items/pakshi/pakkshi (6).jpg", "/prods/silver-items/pakshi/pakkshi (7).jpg", "/prods/silver-items/pakshi/pakkshi (8).jpg", "/prods/silver-items/pakshi/pakkshi (9).jpg", "/prods/silver-items/pakshi/pakkshi (10).jpg", "/prods/silver-items/pakshi/pakkshi (11).jpg"],
    description: 'Stunning Silver Pakshi',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '31',
    name: 'Pen',
    category: 'silver-items',
    // price: 125000,
    images: ['/prods/silver-items/pen/pen (1).jpg', '/prods/silver-items/pen/pen (2).jpg', "/prods/silver-items/pen/pen (3).jpg", "/prods/silver-items/pen/pen (4).jpg", "/prods/silver-items/pen/pen (5).jpg", "/prods/silver-items/pen/pen (6).jpg", "/prods/silver-items/pen/pen (7).jpg", "/prods/silver-items/pen/pen (8).jpg", "/prods/silver-items/pen/pen (9).jpg", "/prods/silver-items/pen/pen (10).jpg", "/prods/silver-items/pen/pen (11).jpg"],
    description: 'Stunning Silver Pen',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '32',
    name: 'Ramjhara',
    category: 'silver-items',
    // price: 125000,
    images: ['/prods/silver-items/ramjhara/ramjhara (1).jpg', '/prods/silver-items/ramjhara/ramjhara (2).jpg', "/prods/silver-items/ramjhara/ramjhara (3).jpg", "/prods/silver-items/ramjhara/ramjhara (4).jpg"],
    description: 'Stunning Silver Ramjhara',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '33',
    name: 'Rath',
    category: 'silver-items',
    // price: 125000,
    images: ['/prods/silver-items/rath/surya-god-rath (1).jpg', '/prods/silver-items/rath/surya-god-rath (2).jpg', "/prods/silver-items/rath/surya-god-rath (3).jpg", "/prods/silver-items/rath/surya-god-rath (4).jpg", "/prods/silver-items/rath/surya-god-rath (5).jpg", "/prods/silver-items/rath/surya-god-rath (6).jpg", "/prods/silver-items/rath/surya-god-rath (7).jpg", "/prods/silver-items/rath/surya-god-rath (8).jpg", "/prods/silver-items/rath/surya-god-rath (9).jpg", "/prods/silver-items/rath/surya-god-rath (10).jpg", "/prods/silver-items/rath/surya-god-rath (11).jpg"],
    description: 'Stunning Silver Rath',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '34',
    name: 'Sada Deepak',
    category: 'silver-items',
    // price: 125000,
    images: ['/prods/silver-items/sada-deepak/sada-deepak (1).jpg', '/prods/silver-items/sada-deepak/sada-deepak (2).jpg', "/prods/silver-items/sada-deepak/sada-deepak (3).jpg", "/prods/silver-items/sada-deepak/sada-deepak (4).jpg", "/prods/silver-items/sada-deepak/sada-deepak (5).jpg", "/prods/silver-items/sada-deepak/sada-deepak (6).jpg", "/prods/silver-items/sada-deepak/sada-deepak (7).jpg", "/prods/silver-items/sada-deepak/sada-deepak (8).jpg", "/prods/silver-items/sada-deepak/sada-deepak (9).jpg", "/prods/silver-items/sada-deepak/sada-deepak (10).jpg", "/prods/silver-items/sada-deepak/sada-deepak (11).jpg"],
    description: 'Stunning Silver Sada Deepak',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '35',
    name: 'Sadi Pin',
    category: 'silver-items',
    // price: 125000,
    images: ['/prods/silver-items/sadi-pin/sadi-pin (1).jpg', '/prods/silver-items/sadi-pin/sadi-pin (2).jpg', "/prods/silver-items/sadi-pin/sadi-pin (3).jpg", "/prods/silver-items/sadi-pin/sadi-pin (4).jpg", "/prods/silver-items/sadi-pin/sadi-pin (5).jpg", "/prods/silver-items/sadi-pin/sadi-pin (6).jpg", "/prods/silver-items/sadi-pin/sadi-pin (7).jpg", "/prods/silver-items/sadi-pin/sadi-pin (8).jpg", "/prods/silver-items/sadi-pin/sadi-pin (9).jpg", "/prods/silver-items/sadi-pin/sadi-pin (10).jpg", "/prods/silver-items/sadi-pin/sadi-pin (11).jpg"],
    description: 'Stunning Silver Sadi Pin',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '36',
    name: 'Shivling Jalhari',
    category: 'silver-items',
    // price: 125000,
    images: ['/prods/silver-items/shivling-jalheri/shivling-jalheri (1).jpg', '/prods/silver-items/shivling-jalheri/shivling-jalheri (2).jpg', "/prods/silver-items/shivling-jalheri/shivling-jalheri (3).jpg", "/prods/silver-items/shivling-jalheri/shivling-jalheri (4).jpg", "/prods/silver-items/shivling-jalheri/shivling-jalheri (5).jpg"],
    description: 'Stunning Silver Shivling Jalhari',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '37',
    name: 'Shivling Jhari',
    category: 'silver-items',
    // price: 125000,
    images: ['/prods/silver-items/shivling-jhari/shivlink-jhari (1).jpg', '/prods/silver-items/shivling-jhari/shivlink-jhari (2).jpg', "/prods/silver-items/shivling-jhari/shivlink-jhari (3).jpg", "/prods/silver-items/shivling-jhari/shivlink-jhari (4).jpg", "/prods/silver-items/shivling-jhari/shivlink-jhari (5).jpg"],
    description: 'Stunning Silver Shivling Jhari',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '38',
    name: 'Shree Shyam Nishan',
    category: 'silver-items',
    // price: 125000,
    images: ['/prods/silver-items/shree-shyam-nishan/shri-shyam-nishan (1).jpg', '/prods/silver-items/shree-shyam-nishan/shri-shyam-nishan (2).jpg', '/prods/silver-items/shree-shyam-nishan/shri-shyam-nishan (3).jpg'],
    description: 'Stunning Silver Shree Shyam Nishan',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '39',
    name: 'Sighdi Borsi',
    category: 'silver-items',
    // price: 125000,
    images: ['/prods/silver-items/sighdi-borsi/sighadi (1).jpg', '/prods/silver-items/sighdi-borsi/sighadi (2).jpg', '/prods/silver-items/sighdi-borsi/sighadi (3).jpg'],
    description: 'Stunning Silver Sighdi Borsi',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '40',
    name: 'Sindoor Dani',
    category: 'silver-items',
    // price: 125000,
    images: ['/prods/silver-items/sindoor-dani/sindoor-dani (1).jpg', '/prods/silver-items/sindoor-dani/sindoor-dani (2).jpg', '/prods/silver-items/sindoor-dani/sindoor-dani (3).jpg', '/prods/silver-items/sindoor-dani/sindoor-dani (4).jpg', '/prods/silver-items/sindoor-dani/sindoor-dani (5).jpg'],
    description: 'Stunning Silver Sindoor Dani',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '41',
    name: 'Star Deepak',
    category: 'silver-items',
    // price: 125000,
    images: ['/prods/silver-items/Star-deepak/star-deepak (1).jpg', '/prods/silver-items/Star-deepak/star-deepak (2).jpg', '/prods/silver-items/Star-deepak/star-deepak (3).jpg', '/prods/silver-items/Star-deepak/star-deepak (4).jpg',],
    description: 'Stunning Silver Star Deepak',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '42',
    name: 'Suaa Pinjra',
    category: 'silver-items',
    // price: 125000,
    images: ['/prods/silver-items/suaa-pinjra/sua-pinjara (1).jpg', '/prods/silver-items/suaa-pinjra/sua-pinjara (2).jpg', '/prods/silver-items/suaa-pinjra/sua-pinjara (3).jpg',],
    description: 'Stunning Silver Suaa Pinjra',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '43',
    name: 'Thos Murti',
    category: 'silver-items',
    // price: 125000,
    images: ['/prods/silver-items/thos-moorti/thos-moorti (1).jpg', '/prods/silver-items/thos-moorti/thos-moorti (2).jpg', '/prods/silver-items/thos-moorti/thos-moorti (3).jpg', '/prods/silver-items/thos-moorti/thos-moorti (4).jpg',],
    description: 'Stunning Silver Thos Murti',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '44',
    name: 'Tulsi Gamla',
    category: 'silver-items',
    // price: 125000,
    images: ['/prods/silver-items/tulsi-gamla/tulsi-gamla (1).jpg', '/prods/silver-items/tulsi-gamla/tulsi-gamla (2).jpg', '/prods/silver-items/tulsi-gamla/tulsi-gamla (3).jpg', '/prods/silver-items/tulsi-gamla/tulsi-gamla (4).jpg', '/prods/silver-items/tulsi-gamla/tulsi-gamla (5).jpg', '/prods/silver-items/tulsi-gamla/tulsi-gamla (6).jpg', '/prods/silver-items/tulsi-gamla/tulsi-gamla (7).jpg', '/prods/silver-items/tulsi-gamla/tulsi-gamla (8).jpg', '/prods/silver-items/tulsi-gamla/tulsi-gamla (9).jpg', '/prods/silver-items/tulsi-gamla/tulsi-gamla (10).jpg', '/prods/silver-items/tulsi-gamla/tulsi-gamla (11).jpg', '/prods/silver-items/tulsi-gamla/tulsi-gamla (12).jpg', '/prods/silver-items/tulsi-gamla/tulsi-gamla (13).jpg', '/prods/silver-items/tulsi-gamla/tulsi-gamla (14).jpg',],
    description: 'Stunning Silver Tulsi Gamla',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '45',
    name: 'Two Side Dibbi',
    category: 'silver-items',
    // price: 125000,
    images: ['/prods/silver-items/two-side-dibbi/two-side-dibbi (1).jpg', '/prods/silver-items/two-side-dibbi/two-side-dibbi (2).jpg', '/prods/silver-items/two-side-dibbi/two-side-dibbi (3).jpg', '/prods/silver-items/two-side-dibbi/two-side-dibbi (4).jpg', '/prods/silver-items/two-side-dibbi/two-side-dibbi (5).jpg', '/prods/silver-items/two-side-dibbi/two-side-dibbi (6).jpg', '/prods/silver-items/two-side-dibbi/two-side-dibbi (7).jpg', '/prods/silver-items/two-side-dibbi/two-side-dibbi (8).jpg', '/prods/silver-items/two-side-dibbi/two-side-dibbi (9).jpg'],
    description: 'Stunning Silver Tulsi Gamla',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '1',
    name: 'Laddu Gopal Balti',
    category: 'laddu-gopal-items',
    // price: 125000,
    images: ['/prods/laddu-gopal-items/laddu-gopal-balti/laddu-gopal-balti (1).jpg', '/prods/laddu-gopal-items/laddu-gopal-balti/laddu-gopal-balti (2).jpg', '/prods/laddu-gopal-items/laddu-gopal-balti/laddu-gopal-balti (3).jpg', '/prods/laddu-gopal-items/laddu-gopal-balti/laddu-gopal-balti (4).jpg', '/prods/laddu-gopal-items/laddu-gopal-balti/laddu-gopal-balti (5).jpg'],
    description: 'Stunning Laddu Gopal Balti',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '2',
    name: 'Laddu Gopal Balti Pichkari',
    category: 'laddu-gopal-items',
    // price: 125000,
    images: ['/prods/laddu-gopal-items/laddu-gopal-balti-pichkari/laddu-gopal-balti-pichkari (1).jpg', '/prods/laddu-gopal-items/laddu-gopal-balti-pichkari/laddu-gopal-balti-pichkari (2).jpg', '/prods/laddu-gopal-items/laddu-gopal-balti-pichkari/laddu-gopal-balti-pichkari (3).jpg', '/prods/laddu-gopal-items/laddu-gopal-balti-pichkari/laddu-gopal-balti-pichkari (4).jpg', '/prods/laddu-gopal-items/laddu-gopal-balti-pichkari/laddu-gopal-balti-pichkari (5).jpg',],
    description: 'Stunning Laddu Gopal Balti Pichkari',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '3',
    name: 'Laddu Gopal Bansuri',
    category: 'laddu-gopal-items',
    // price: 125000,
    images: ['/prods/laddu-gopal-items/laddu-gopal-bansuri/laddu-gopal-bansuri (1).jpg', '/prods/laddu-gopal-items/laddu-gopal-bansuri/laddu-gopal-bansuri (2).jpg', '/prods/laddu-gopal-items/laddu-gopal-bansuri/laddu-gopal-bansuri (3).jpg', '/prods/laddu-gopal-items/laddu-gopal-bansuri/laddu-gopal-bansuri (4).jpg', '/prods/laddu-gopal-items/laddu-gopal-bansuri/laddu-gopal-bansuri (5).jpg', '/prods/laddu-gopal-items/laddu-gopal-bansuri/laddu-gopal-bansuri (6).jpg', '/prods/laddu-gopal-items/laddu-gopal-bansuri/laddu-gopal-bansuri (7).jpg', '/prods/laddu-gopal-items/laddu-gopal-bansuri/laddu-gopal-bansuri (8).jpg', '/prods/laddu-gopal-items/laddu-gopal-bansuri/laddu-gopal-bansuri (9).jpg', '/prods/laddu-gopal-items/laddu-gopal-bansuri/laddu-gopal-bansuri (10).jpg', '/prods/laddu-gopal-items/laddu-gopal-bansuri/laddu-gopal-bansuri (11).jpg', '/prods/laddu-gopal-items/laddu-gopal-bansuri/laddu-gopal-bansuri (12).jpg', '/prods/laddu-gopal-items/laddu-gopal-bansuri/laddu-gopal-bansuri (13).jpg',],
    description: 'Stunning Laddu Gopal Bansuri',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '4',
    name: 'Laddu Gopal Hath Kada',
    category: 'laddu-gopal-items',
    // price: 125000,
    images: ['/prods/laddu-gopal-items/laddu-gopal-hath-kada/laddu-gopal-hath-kada (1).jpg', '/prods/laddu-gopal-items/laddu-gopal-hath-kada/laddu-gopal-hath-kada (2).jpg', '/prods/laddu-gopal-items/laddu-gopal-hath-kada/laddu-gopal-hath-kada (3).jpg', '/prods/laddu-gopal-items/laddu-gopal-hath-kada/laddu-gopal-hath-kada (4).jpg',],
    description: 'Stunning Laddu Gopal Hath Kada',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '5',
    name: 'Laddu Gopal Jhula',
    category: 'laddu-gopal-items',
    // price: 125000,
    images: ['/prods/laddu-gopal-items/laddu-gopal-jhula/laddu-gopal-jhula (1).jpg', '/prods/laddu-gopal-items/laddu-gopal-jhula/laddu-gopal-jhula (2).jpg', '/prods/laddu-gopal-items/laddu-gopal-jhula/laddu-gopal-jhula (3).jpg', '/prods/laddu-gopal-items/laddu-gopal-jhula/laddu-gopal-jhula (4).jpg', '/prods/laddu-gopal-items/laddu-gopal-jhula/laddu-gopal-jhula (5).jpg', '/prods/laddu-gopal-items/laddu-gopal-jhula/laddu-gopal-jhula (6).jpg', '/prods/laddu-gopal-items/laddu-gopal-jhula/laddu-gopal-jhula (7).jpg', '/prods/laddu-gopal-items/laddu-gopal-jhula/laddu-gopal-jhula (8).jpg'],
    description: 'Stunning Laddu Gopal Jhula',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '6',
    name: 'Laddu Gopal Makan',
    category: 'laddu-gopal-items',
    // price: 125000,
    images: ['/prods/laddu-gopal-items/laddu-gopal-makan/laddu-gopal-makan (1).jpg', '/prods/laddu-gopal-items/laddu-gopal-makan/laddu-gopal-makan (2).jpg', '/prods/laddu-gopal-items/laddu-gopal-makan/laddu-gopal-makan (3).jpg', '/prods/laddu-gopal-items/laddu-gopal-makan/laddu-gopal-makan (4).jpg'],
    description: 'Stunning Laddu Gopal Makan',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '7',
    name: 'Laddu Gopal Mathdi',
    category: 'laddu-gopal-items',
    // price: 125000,
    images: ['/prods/laddu-gopal-items/laddu-gopal-mathdi/laddu-gopal-mathdi (1).jpg', '/prods/laddu-gopal-items/laddu-gopal-mathdi/laddu-gopal-mathdi (2).jpg'],
    description: 'Stunning Laddu Gopal Mathdi',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '8',
    name: 'Laddu Gopal per Kadiya',
    category: 'laddu-gopal-items',
    // price: 125000,
    images: ['/prods/laddu-gopal-items/laddu-gopal-pair-kadiya/laddu-gopal-pair-kadiya (1).jpg', '/prods/laddu-gopal-items/laddu-gopal-pair-kadiya/laddu-gopal-pair-kadiya (2).jpg'],
    description: 'Stunning Laddu Gopal Per Kadiya',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '9',
    name: 'Laddu Gopal Pankhi',
    category: 'laddu-gopal-items',
    // price: 125000,
    images: ['/prods/laddu-gopal-items/laddu-gopal-pankhi/laddu-gopal-pankhi (1).jpg', '/prods/laddu-gopal-items/laddu-gopal-pankhi/laddu-gopal-pankhi (2).jpg', '/prods/laddu-gopal-items/laddu-gopal-pankhi/laddu-gopal-pankhi (3).jpg'],
    description: 'Stunning Laddu Gopal Per Kadiya',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '10',
    name: 'Laddu Gopal Sinhasan',
    category: 'laddu-gopal-items',
    // price: 125000,
    images: ['/prods/laddu-gopal-items/laddu-gopal-sinhasan/laddu-gopal-sinhasan (1).jpg', '/prods/laddu-gopal-items/laddu-gopal-sinhasan/laddu-gopal-sinhasan (2).jpg', '/prods/laddu-gopal-items/laddu-gopal-sinhasan/laddu-gopal-sinhasan (3).jpg', '/prods/laddu-gopal-items/laddu-gopal-sinhasan/laddu-gopal-sinhasan (4).jpg', '/prods/laddu-gopal-items/laddu-gopal-sinhasan/laddu-gopal-sinhasan (5).jpg', '/prods/laddu-gopal-items/laddu-gopal-sinhasan/laddu-gopal-sinhasan (6).jpg', '/prods/laddu-gopal-items/laddu-gopal-sinhasan/laddu-gopal-sinhasan (7).jpg',],
    description: 'Stunning Laddu Gopal Sinhasan',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  {
    id: '11',
    name: 'Laddu Gopal Tippad',
    category: 'laddu-gopal-items',
    // price: 125000,
    images: ['/prods/laddu-gopal-items/laddu-gopal-tippad/laddu-gopal-tippad (1).jpg', '/prods/laddu-gopal-items/laddu-gopal-tippad/laddu-gopal-tippad (2).jpg'],
    description: 'Stunning Laddu Gopal Sinhasan',
    material: 'Silver',
    weight: '',
    purity: '',
    inStock: true,
    featured: true,
  },
  // Add more sample products as needed
];

export const contactInfo: ContactInfo = {
  phone: '+91 9667177704',
  whatsapp: '6377209425 ',
  email: 'info@priyanshjewellers.com',
  address: 'Priyansh Jewellers, Sona Patti, Naya Bazar, Sujangarh 331507',
  hours: {
    weekdays: '10:00 AM - 8:00 PM',
    weekends: '10:00 AM - 9:00 PM',
  },
};

export const testimonials = [
  {
    id: '1',
    name: 'Priya Sharma',
    text: 'Beautiful jewelry with excellent craftsmanship. The gold quality is outstanding and the designs are unique.',
    rating: 5,
    location: 'Sujangarh',
  },
  {
    id: '2',
    name: 'Raj Patel',
    text: 'Trusted jeweller with transparent pricing. Bought my wedding rings here and couldn\'t be happier.',
    rating: 5,
    location: 'Sujangarh',
  },
  {
    id: '3',
    name: 'Anita Gupta',
    text: 'Excellent customer service and wide variety of traditional designs. Highly recommended for special occasions.',
    rating: 5,
    location: 'Sujangarh',
  },
];